// Fail the boot when the web tier's *derived* inputs are missing or stale.
//
// `src/wasm/` (jco transpile) and `src/gen/` (es-lite messages) are generated by
// the Makefile and gitignored. `make dev-web` / `make verify-web` regenerate
// them — but `npm run dev`, `vite build`, and Playwright's webServer all invoke
// Vite directly and would happily serve whatever is lying around. Two failure
// modes that costs you:
//
//   missing — a fresh clone gets a blank screen and a confusing runtime error
//   stale   — you edit commands.proto, reload, and silently get the OLD schema,
//             which looks like an engine bug rather than a build one
//
// The second is the dangerous one: nothing errors, the bytes just disagree.
//
// This deliberately does NOT run `make` for you. An implicit rebuild inside a
// dev server is a surprise (it can take a minute of TinyGo), and a wrong guess
// about what to rebuild is worse than a clear instruction.
import { readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import type { Plugin } from "vite";

interface Check {
  /** What the user sees. */
  label: string;
  /** Generated tree that must exist and be at least as new as its sources. */
  derived: string;
  /** Source trees it is generated from. */
  sources: string[];
  /** Only files matching this count as sources. */
  match: RegExp;
  /** The command that regenerates it. */
  fix: string;
}

/** Newest mtime under a path, or 0 if nothing matches / it does not exist. */
function newestMtime(path: string, match?: RegExp): number {
  let stat;
  try {
    stat = statSync(path);
  } catch {
    return 0;
  }
  if (stat.isFile()) return match && !match.test(path) ? 0 : stat.mtimeMs;

  let newest = 0;
  for (const entry of readdirSync(path, { withFileTypes: true })) {
    // node_modules and dot-dirs are never sources here.
    if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
    newest = Math.max(newest, newestMtime(join(path, entry.name), match));
  }
  return newest;
}

export function freshness(repo: string): Plugin {
  const checks: Check[] = [
    {
      label: "src/gen (es-lite messages)",
      derived: resolve(repo, "hosts/web/src/gen"),
      sources: [resolve(repo, "proto"), resolve(repo, "dlc-platform/proto")],
      match: /\.proto$/,
      fix: "make gen-web",
    },
    {
      label: "src/wasm (jco-transpiled component)",
      derived: resolve(repo, "hosts/web/src/wasm"),
      sources: [
        resolve(repo, "engine"),
        resolve(repo, "cmd/engine-component"),
        resolve(repo, "dlc-platform/wit"),
        resolve(repo, "dlc-platform"),
      ],
      match: /\.(go|wit)$/,
      fix: "make build-wasm",
    },
  ];

  return {
    name: "dlc:freshness",
    enforce: "pre",
    buildStart() {
      if (process.env.DLC_SKIP_FRESHNESS === "1") return;

      const problems: string[] = [];
      for (const check of checks) {
        const derived = newestMtime(check.derived);
        if (derived === 0) {
          problems.push(`  ${check.label} is MISSING — run: ${check.fix}`);
          continue;
        }
        const source = Math.max(
          ...check.sources.map((s) => newestMtime(s, check.match)),
        );
        if (source > derived) {
          const age = Math.round((source - derived) / 1000);
          problems.push(
            `  ${check.label} is STALE by ${age}s — its sources changed since it was built. Run: ${check.fix}`,
          );
        }
      }
      if (problems.length === 0) return;

      throw new Error(
        [
          "",
          "The web tier's generated inputs are not usable:",
          ...problems,
          "",
          "These are derived and gitignored; the Makefile owns them.",
          "`make dev-web` and `make verify-web` regenerate them for you.",
          "Set DLC_SKIP_FRESHNESS=1 to bypass this check (you will get stale bytes).",
          "",
        ].join("\n"),
      );
    },
  };
}
