// Code generated by cmd/gen-names from dlc-platform/names/. DO NOT EDIT.
//
// The RULES are here; the REASONS are in names.rs, beside the API that uses
// them. Editing this file is a mistake the -check mode will catch.

#![allow(dead_code)]

/// The portable profile's longest single component.
pub const COMPONENT_MAX: usize = 64;

/// The portable profile's longest whole path.
pub const PATH_MAX: usize = 255;

/// How many characters a FAT 8.3 short name keeps.
pub const SHORT_STEM_LEN: usize = 8;

/// Whether a byte may appear in a portable name.
pub const fn portable_name_char(c: u8) -> bool {
    matches!(c, b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.')
}

/// Map a byte to what a FAT 8.3 field may hold.
pub const fn short_name_char(c: u8) -> u8 {
    let c = c.to_ascii_uppercase();
    if matches!(c, b'A'..=b'Z' | b'0'..=b'9' | b'$' | b'%' | b'-' | b'_' | b'@' | b'~' | b'`' | b'!' | b'(' | b')' | b'{' | b'}' | b'^' | b'#' | b'&') {
        c
    } else {
        b'_'
    }
}

/// A byte that may not START a component.
pub const fn bad_edge_first(c: u8) -> bool {
    matches!(c, b'.' | b'-')
}

/// A byte that may not END a component.
pub const fn bad_edge_last(c: u8) -> bool {
    matches!(c, b'.' | b'-')
}

/// Names Windows refuses, with or without an extension.
pub const RESERVED_DEVICES: [&str; 22] = [
    "con",
    "prn",
    "aux",
    "nul",
    "com1",
    "com2",
    "com3",
    "com4",
    "com5",
    "com6",
    "com7",
    "com8",
    "com9",
    "lpt1",
    "lpt2",
    "lpt3",
    "lpt4",
    "lpt5",
    "lpt6",
    "lpt7",
    "lpt8",
    "lpt9",
];

/// Per-profile component limit.
pub const fn profile_component_max(profile: &str) -> usize {
    if str_eq(profile, "fat") {
        return 64;
    }
    if str_eq(profile, "portable") {
        return 64;
    }
    if str_eq(profile, "posix") {
        return 255;
    }
    COMPONENT_MAX
}

/// Per-profile path limit.
pub const fn profile_path_max(profile: &str) -> usize {
    if str_eq(profile, "fat") {
        return 255;
    }
    if str_eq(profile, "portable") {
        return 255;
    }
    if str_eq(profile, "posix") {
        return 4096;
    }
    PATH_MAX
}

/// `WorldName` in world_name.proto. Generated from the same rows, so the
/// badge cannot report a number the schema does not name.
pub const WORLD_NAME_UNSPECIFIED: u32 = 0;
pub const WORLD_NAME_UNKNOWN: u32 = 1;
pub const WORLD_NAME_NATIVE: u32 = 2;
pub const WORLD_NAME_BROWSER: u32 = 3;
pub const WORLD_NAME_BADGE_NORMAL: u32 = 4;
pub const WORLD_NAME_BADGE_MINIMAL: u32 = 5;
pub const WORLD_NAME_BADGE_BADGER_NORMAL: u32 = 6;
pub const WORLD_NAME_BADGE_BADGER_MINIMAL: u32 = 7;

/// The registry, minus the two non-worlds.
pub const KNOWN_WORLDS: [&str; 6] = [
    "native",
    "browser",
    "badge-normal",
    "badge-minimal",
    "badge-badger-normal",
    "badge-badger-minimal",
];

/// A world's rule set. Both non-worlds and anything unrecognised FAIL CLOSED
/// onto the strictest profile.
pub const fn world_name_profile(world: &str) -> &'static str {
    if str_eq(world, "native") {
        return "portable";
    }
    if str_eq(world, "browser") {
        return "portable";
    }
    if str_eq(world, "badge-normal") {
        return "fat";
    }
    if str_eq(world, "badge-minimal") {
        return "fat";
    }
    if str_eq(world, "badge-badger-normal") {
        return "fat";
    }
    if str_eq(world, "badge-badger-minimal") {
        return "fat";
    }
    "portable"
}

/// `str` comparison usable in a `const fn`, which `==` is not.
const fn str_eq(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}
