//! Every enum value the wire uses, generated from the `.proto` files.
//!
//! # This file holds no numbers either
//!
//! They are generated by `protoc-gen-dlc-registry` into `dlc-platform/gen/rust`
//! and included here, because this crate hand-decodes protobuf by comparing a
//! varint against a constant.
//!
//! # Why hand-decoded at all — and it is NOT "no_std cannot run protoc"
//!
//! That is what this comment used to say, and it was wrong twice over: protoc
//! runs on the BUILD HOST, not on the badge, and a `build.rs` could generate
//! Rust message types exactly as it generates these constants.
//!
//! The real constraint is narrower and lives in one place. Stages 1 to 3 have no
//! allocator — the heap arena cannot be chosen until PSRAM has been probed — and
//! `prost`'s generated structs hold `String` and `Vec<u8>`. The control channel
//! has to answer BEFORE that, which is why `Cursor` exists and why a refusal is
//! built on the stack. Generated types would be usable everywhere after stage 4
//! and unusable in the window that matters most.
//!
//! # What would change that
//!
//! Crates built for this: `micropb` and `femtopb` generate `no_std` types with
//! fixed-capacity containers and no allocator. Either would let the badge decode
//! by TYPE rather than by field number, which is a bigger win than these
//! constants — a wrong field number is a worse failure than a wrong value, and
//! generated types remove both.
//!
//! Not done, and deliberately not claimed as impossible.
//!
//! # What retyping them cost
//!
//! There were 41 of these written out by hand, and one was wrong for a day:
//! `TextOutlet` was transcribed as `DISPLAY = 2, UART = 3` — alphabetical order
//! rather than declared order — so a badge writing to its own screen told every
//! client it was writing to a serial port. Nothing caught it. Both values are
//! legal, the frame checksummed, and the enum name printed cleanly at the far
//! end; only a log line saying `display` on the same screen disagreed.
//!
//! Generating them removes the transcription step that made that possible.

// INCLUDED RATHER THAN A MODULE PATH, because the generated tree lives beside
// the crate rather than inside it — buf writes it, cargo does not.
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../gen/rust/devalbo/ilc/v1/control.enums.rs"));

/// FIELD NUMBERS, generated from the same .proto as the values above.
///
/// The enums removed transcribed VALUES. These remove transcribed IDENTITIES,
/// and the failure is worse: a wrong value mislabels a field, a wrong number
/// puts the bytes somewhere else entirely — skipped as unknown, or decoded as a
/// different field of compatible wire type, silently.
pub mod fields {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../gen/rust/devalbo/ilc/v1/control.fields.rs"
    ));
}

pub mod manifest {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../gen/rust/devalbo/ilc/v1/world_manifest.enums.rs"
    ));

    pub mod fields {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../gen/rust/devalbo/ilc/v1/world_manifest.fields.rs"
        ));
    }
}

/// THE DLC STANDARD VOCABULARY — what apps and worlds share.
///
/// Its own module because it is its own package: `devalbo.dlc.std.v1`, vendored
/// into every app, as opposed to `devalbo.ilc.v1` which is host-facing and which
/// an app never sees.
pub mod dlc_std {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../gen/rust/devalbo/dlc/std/v1/status.enums.rs"
    ));
}

pub mod platform {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../gen/rust/devalbo/ilc/v1/platform.enums.rs"
    ));

    /// METHOD IDS, generated. The badge sends `execute(method, bytes)`, so it
    /// needs these as much as any tier — and was writing them out by hand.
    ///
    /// `METHOD_ID_` rather than `METHOD_`: in SCREAMING_SNAKE the shorter name
    /// reads as "the version of the method" at least as easily as "the method id
    /// of Version", and `Version` being a noun is what makes it land wrong.
    pub mod methods {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../gen/rust/devalbo/ilc/v1/platform.methods.rs"
        ));
    }

    pub mod fields {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../gen/rust/devalbo/ilc/v1/platform.fields.rs"
        ));
    }
}
