//! Every enum value the wire uses, generated from the `.proto` files.
//!
//! # This file holds no numbers either
//!
//! They are generated by `protoc-gen-dlc-registry` into `dlc-platform/gen/rust`
//! and included here, because this crate is `no_std`: it cannot run protoc, and
//! it hand-decodes protobuf by comparing a varint against a constant.
//!
//! # What retyping them cost
//!
//! There were 41 of these written out by hand, and one was wrong for a day:
//! `TextOutlet` was transcribed as `DISPLAY = 2, UART = 3` — alphabetical order
//! rather than declared order — so a badge writing to its own screen told every
//! client it was writing to a serial port. Nothing caught it. Both values are
//! legal, the frame checksummed, and the enum name printed cleanly at the far
//! end; only a log line saying `display` on the same screen disagreed.
//!
//! Generating them removes the transcription step that made that possible.

// INCLUDED RATHER THAN A MODULE PATH, because the generated tree lives beside
// the crate rather than inside it — buf writes it, cargo does not.
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/../gen/rust/devalbo/ilc/v1/control.enums.rs"));

pub mod manifest {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../gen/rust/devalbo/ilc/v1/world_manifest.enums.rs"
    ));
}

pub mod platform {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../gen/rust/devalbo/ilc/v1/platform.enums.rs"
    ));
}
