use std::fmt::Write as _;

use anyhow::Result;
use std::path::Path;

use crate::emit::write_generated;
use crate::ir::{Interface, Package, TypeRef};

const HEADER: &str = "# Generated by ilc-compiler. Do not edit.\n\nfrom __future__ import annotations\n\nfrom typing import Protocol, runtime_checkable\n\n";

pub fn emit_package(pkg: &Package) -> String {
    let mut out = String::from(HEADER);
    for iface in &pkg.interfaces {
        emit_interface(&mut out, iface);
        out.push('\n');
    }
    out
}

fn emit_interface(out: &mut String, iface: &Interface) {
    writeln!(out, "@runtime_checkable").unwrap();
    writeln!(out, "class {}(Protocol):", iface.name).unwrap();
    for func in &iface.functions {
        emit_function(out, func);
    }
    out.push('\n');
}

fn emit_function(out: &mut String, func: &crate::ir::Function) {
    write!(out, "    async def {}(self", func.name).unwrap();
    for param in &func.params {
        write!(out, ", {}: {}", param.name, py_type(&param.ty)).unwrap();
    }
    write!(out, ") -> ").unwrap();
    match &func.result {
        None => writeln!(out, "None: ...").unwrap(),
        Some(ty) => writeln!(out, "{}: ...", py_type(ty)).unwrap(),
    }
}

fn py_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::String => "str".to_string(),
        TypeRef::Option(inner) => format!("{} | None", py_type(inner)),
        TypeRef::Interface(name) => name.clone(),
    }
}

pub fn write_python(pkg: &Package, out_path: &Path) -> Result<()> {
    write_generated(out_path, &emit_package(pkg))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::wit::load_package;
    use std::path::Path;

    #[test]
    fn golden_python() {
        let wit = Path::new(env!("CARGO_MANIFEST_DIR")).join("../wit");
        let pkg = load_package(&wit).unwrap();
        insta::assert_snapshot!(emit_package(&pkg));
    }
}
