use std::fmt::Write as _;

use anyhow::Result;
use std::path::Path;

use crate::emit::write_generated;
use crate::ir::{Interface, Package, TypeRef};

const HEADER: &str = "// Generated by ilc-compiler. Do not edit.\n\nuse async_trait::async_trait;\n\n";

pub fn emit_package(pkg: &Package) -> String {
    let mut out = String::from(HEADER);
    for iface in &pkg.interfaces {
        emit_interface(&mut out, iface);
        out.push('\n');
    }
    out
}

fn emit_interface(out: &mut String, iface: &Interface) {
    writeln!(out, "#[async_trait]").unwrap();
    writeln!(out, "pub trait {}: Send + Sync {{", iface.name).unwrap();
    for func in &iface.functions {
        emit_function(out, func);
    }
    writeln!(out, "}}").unwrap();
}

fn emit_function(out: &mut String, func: &crate::ir::Function) {
    write!(out, "    async fn {}(&self", func.name).unwrap();
    for param in &func.params {
        write!(out, ", {}: {}", param.name, rs_type(&param.ty, true)).unwrap();
    }
    write!(out, ")").unwrap();
    match &func.result {
        None => writeln!(out, ";").unwrap(),
        Some(ty) => writeln!(out, " -> {};", rs_type(ty, false)).unwrap(),
    }
}

/// `param` = reference types for function parameters.
fn rs_type(ty: &TypeRef, param: bool) -> String {
    match ty {
        TypeRef::String => {
            if param {
                "&str".to_string()
            } else {
                "String".to_string()
            }
        }
        TypeRef::Option(inner) => format!("Option<{}>", rs_type(inner, false)),
        TypeRef::Interface(name) => {
            if param {
                format!("&dyn {name}")
            } else {
                format!("Box<dyn {name} + Send + '_>")
            }
        }
    }
}

pub fn write_rust(pkg: &Package, out_path: &Path) -> Result<()> {
    write_generated(out_path, &emit_package(pkg))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::wit::load_package;
    use std::path::Path;

    #[test]
    fn golden_rust() {
        let wit = Path::new(env!("CARGO_MANIFEST_DIR")).join("../wit");
        let pkg = load_package(&wit).unwrap();
        insta::assert_snapshot!(emit_package(&pkg));
    }
}
