use std::fmt::Write as _;
use std::path::Path;

use anyhow::Result;

use crate::emit::write_generated;
use crate::ir::{Interface, Package, TypeRef};

const HEADER: &str = "/** Generated by ilc-compiler. Do not edit. */\n";

pub fn emit_package(pkg: &Package) -> String {
    let mut out = String::from(HEADER);
    for iface in &pkg.interfaces {
        emit_interface(&mut out, iface);
        out.push('\n');
    }
    out
}

fn emit_interface(out: &mut String, iface: &Interface) {
    writeln!(out, "export interface {} {{", iface.name).unwrap();
    for func in &iface.functions {
        emit_function(out, func);
    }
    writeln!(out, "}}").unwrap();
}

fn emit_function(
    out: &mut String,
    func: &crate::ir::Function,
) {
    write!(out, "  {}(", func.name).unwrap();
    for (i, param) in func.params.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        write!(out, "{}: {}", param.name, ts_type(&param.ty)).unwrap();
    }
    out.push_str("): ");
    match &func.result {
        None => write!(out, "Promise<void>").unwrap(),
        Some(ty) => write!(out, "Promise<{}>", ts_type(ty)).unwrap(),
    }
    writeln!(out, ";").unwrap();
}

fn ts_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::String => "string".to_string(),
        TypeRef::Option(inner) => format!("{} | null", ts_type(inner)),
        TypeRef::Interface(name) => name.clone(),
    }
}

pub fn write_typescript(pkg: &Package, out_path: &Path) -> Result<()> {
    write_generated(out_path, &emit_package(pkg))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::wit::load_package;
    use std::path::Path;

    #[test]
    fn golden_typescript() {
        let wit = Path::new(env!("CARGO_MANIFEST_DIR")).join("../wit");
        let pkg = load_package(&wit).unwrap();
        let ts = emit_package(&pkg);
        insta::assert_snapshot!(ts);
    }
}
