//! Bring-up as a WATCHABLE SEQUENCE, on the badge's own screen.
//!
//! # Why this exists
//!
//! The firmware already printed a serial log, and where that log *stopped* was
//! the diagnosis — which works, and requires a 3.3 V adapter clipped to two
//! crocodile pads, and requires you to know what the last line implies. For
//! anyone else the badge just sat there.
//!
//! So the bring-up narrates itself: each check announces what it is about to
//! test, runs, and shows `OK` or `FAIL` next to its own name, **paced slowly
//! enough for a human to read**. The screen becomes the diagnosis and the UART
//! becomes the detail — the same information, at two levels of patience.
//!
//! # The ordering is the diagnostic, and that has not changed
//!
//! Each stage assumes the previous one worked, so **the first red line is the
//! answer** and everything after it is noise. That is why stages are announced
//! BEFORE they run: a board that hangs shows the name of what it hung in, which
//! a log that stops does not.
//!
//! # THE STAGES ARE WEIGHTED BY WHAT QEMU CANNOT MODEL
//!
//! Most of this firmware is already green under `make qemu`, at the badge's own
//! pointer width, through this same host: the engine, `deserialize_raw`,
//! instantiation, `execute`. Re-running those on hardware is a regression check,
//! not a discovery.
//!
//! **What the emulator has nothing to say about is the board** — the QSPI PSRAM
//! and its XIP-disabled init, the ST7789 on a bit-banged parallel bus, the
//! backlight, the payload catalog living in real memory-mapped flash, the crystal
//! the UART divisor is derived from, and a Cortex-M33 rather than the M3 QEMU
//! runs. Those are the only checks that carry new information, so they are
//! MARKED (`*`) and counted separately in the verdict.
//!
//! The practical consequence: a run where every `*` passes and something else
//! fails means the emulator and the board disagree, which is a far more
//! interesting bug than a wire being loose.
//!
//! # A STAGE IS ONE LINE, and the compiler is what keeps it that way
//!
//! `stage()` writes `5. instantiate hello ... ` and leaves the line OPEN;
//! `ok()`/`fail()` closes it with the detail and `[OK]`. So a `note()` in
//! between does not merely appear early — it lands *inside* the announcement and
//! strands the result on a line of its own:
//!
//! ```text
//! 5. instantiate hello ...      ILC_TIER=rp2350
//! 2911 KB heap [OK]
//! ```
//!
//! That shipped, in exactly one place, and nothing caught it: the screen is
//! unaffected (notes are UART-only) and this crate is BUILT by CI, never tested —
//! there is no host to run a test on. So the rule is enforced by the type system
//! instead of by a comment: [`Report::stage`] hands back an [`Open`] guard that
//! borrows the report, and `note()` while a stage is open does not compile.
//!
//! # What this deliberately does not do
//!
//! No spinner, no progress bar, no animation. Every frame costs a full-screen
//! worth of bus traffic on a bit-banged parallel panel, and a badge that looks
//! busy while hung is worse than one that plainly stopped.

use core::fmt::{Arguments, Write};

use embedded_graphics::mono_font::ascii::FONT_8X13;
use embedded_graphics::mono_font::MonoTextStyle;
use embedded_graphics::pixelcolor::Rgb565;
use embedded_graphics::prelude::*;

use crate::display::Display;
use crate::world::Status;

// HOW LONG A RESULT STAYS ON SCREEN — a FLASH-TIME choice (`BADGE_BEAT_MS`),
// generated by build.rs.
//
// **Zero by default, and that is the right default.** Normal boot should reach
// the app as fast as the board can; being readable is a debugging mode, not a
// tax on every power-on. At 0 the delay compiles away and the stages still
// appear — they simply scroll past at machine speed, which is exactly what you
// want when nobody is watching and exactly what you do not want on a first
// bring-up. 700 ms is about a comfortable reading beat, putting the whole
// sequence under ten seconds.
include!(concat!(env!("OUT_DIR"), "/beat.rs"));

/// Characters across at `FONT_8X13`: 320 px / 8.
const COLS: i32 = 40;
/// Where the `OK` / `FAIL` column starts, leaving room for a long stage name.
const RESULT_COL: i32 = 30;

const LINE_H: i32 = 14;
const TOP: i32 = 16;

const OK_COLOR: Rgb565 = Rgb565::new(0, 63, 0);
const FAIL_COLOR: Rgb565 = Rgb565::new(31, 0, 0);
const NAME_COLOR: Rgb565 = Rgb565::new(31, 63, 31);
const DIM_COLOR: Rgb565 = Rgb565::new(15, 31, 15);

/// Whether a check can be run anywhere else.
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Scope {
    /// **QEMU cannot model this.** The only stages that carry new information,
    /// because nothing but the board can answer them.
    HardwareOnly,
    /// Already proven green under `make qemu`, at this pointer width, through
    /// this host. A failure here is not "does it work" but "does the BOARD
    /// disagree with the emulator" — narrower, and more surprising.
    Emulated,
}

impl Scope {
    /// `Scope` in control.proto. Written out rather than cast: this enum's
    /// discriminants are a local detail, and the proto numbers are a wire
    /// contract that must not follow a reordering here.
    pub const fn code(self) -> u32 {
        match self {
            Scope::HardwareOnly => dlc_platform_embedded::control::SCOPE_HARDWARE_ONLY,
            Scope::Emulated => dlc_platform_embedded::control::SCOPE_EMULATED,
        }
    }
}

/// Narrates the bring-up to a screen and a UART at once.
///
/// Owns neither the flow nor the checks: `main.rs` still runs them in order,
/// because each one depends on the last and a table of closures would hide that.
/// This only reports.
pub struct Report<'a, U: Write> {
    uart: &'a mut U,
    screen: &'a mut Option<Display>,
    line: i32,
    /// HOW MANY STAGES HAVE RUN — a count, used only for the verdict tally.
    ///
    /// Deliberately NOT the number a stage prints. That number is the stage's own
    /// identity from the `Stage` enum, and the two diverge the moment a stage is
    /// skipped: `VERIFY_PAYLOAD` only runs when a payload is corrupt, so a
    /// healthy boot runs eight stages whose identities go up to nine. Naming this
    /// `stage` was what let one be quietly used for the other.
    ran: u32,
    failures: u32,
    /// Counted apart from the total, because these are the ones worth reporting
    /// to somebody else.
    hardware_checks: u32,
    hardware_passed: u32,
    last_was_hardware: bool,
    /// The open stage's `Scope`, as the proto number, so a note under it is
    /// attributed the same way its stage was.
    scope_code: u32,
    sys_hz: u32,
}

impl<'a, U: Write> Report<'a, U> {
    pub fn new(
        uart: &'a mut U,
        screen: &'a mut Option<Display>,
        sys_hz: u32,
        title: Arguments<'_>,
    ) -> Self {
        let mut report = Self {
            uart,
            screen,
            line: 0,
            ran: 0,
            failures: 0,
            hardware_checks: 0,
            hardware_passed: 0,
            scope_code: 0,
            last_was_hardware: false,
            sys_hz,
        };
        report.clear_screen();
        report.draw(TOP, 0, title, NAME_COLOR);
        report.line = 1;
        let _ = writeln!(report.uart, "\r\n=== DLC badge bring-up ===");
        report
    }

    fn clear_screen(&mut self) {
        if let Some(panel) = self.screen.as_mut() {
            panel.fill(0x0000);
        }
    }

    fn draw(&mut self, y: i32, col: i32, text: Arguments<'_>, color: Rgb565) {
        let Some(panel) = self.screen.as_mut() else {
            return;
        };
        // A stack buffer rather than an allocation: this runs BEFORE the heap is
        // known good, which is the whole point of stage 3 existing.
        let mut buffer = TextBuffer::new();
        let _ = core::fmt::write(&mut buffer, text);
        let style = MonoTextStyle::new(&FONT_8X13, color);
        panel.text(buffer.as_str(), Point::new(col * 8, y), style);
    }

    fn pause(&self) {
        // A zero beat is not "a very short delay" — it is no delay at all, and
        // the branch lets the whole call vanish in the default build.
        if BEAT_MS == 0 {
            return;
        }
        cortex_m::asm::delay(self.sys_hz / 1000 * BEAT_MS);
    }

    fn y(&self) -> i32 {
        TOP + self.line * LINE_H
    }

    /// Enter a PHASE — the high-level step the stages below it belong to.
    ///
    /// # Why this is on the report rather than beside it
    ///
    /// Because there must be exactly one way to advance. The phase was briefly
    /// published by a `progress::enter` call sitting next to the report's stage
    /// calls, which is two trackers for one sequence: the panel showed a flat
    /// list of nine stages while the wire carried a phase nothing on the panel
    /// mentioned, and keeping them agreeing was a discipline rather than a
    /// property.
    ///
    /// Now a phase is announced the same way a stage is — one call that both
    /// SHOWS it and PUBLISHES it — so the log, the panel and `GetWorldState`
    /// cannot disagree about where the world has got to.
    ///
    /// The stage counter keeps running across phases rather than restarting. A
    /// stage number is a position in the whole bring-up, and it is what the log
    /// and the runbook both refer to; restarting it per phase would make "stage
    /// 2" ambiguous in the one place people quote it.
    pub fn phase(&mut self, which: u32, name: Arguments<'_>) {
        let fault = crate::progress::enter(which);
        let y = self.y();
        self.draw(y, 0, format_args!("- {name}"), NAME_COLOR);
        self.line += 1;
        let _ = writeln!(self.uart, "\r\n-- {name} --");
        // A TRANSITION THE WORLD SHOULD NOT HAVE BEEN ABLE TO TAKE.
        //
        // Counted as a FAILURE, so the verdict goes red and the badge says so
        // across a room. This is a firmware bug by construction — the phases are
        // entered from four places in one function — and the alternative to
        // shouting is a badge that quietly reports a phase it is not in, which is
        // worse than the bug it is covering for.
        if let Some((from, to)) = fault {
            self.failures += 1;
            let _ = writeln!(
                self.uart,
                "\r\n!! phase {from} -> {to} is not a transition this world has"
            );
            self.note(format_args!("phase fault: {from} -> {to}"));
        }
    }

    /// Announce what is about to be tested — **before** running it.
    ///
    /// A board that hangs then shows the name of the thing it hung in, which is
    /// the one diagnosis a log that simply stops cannot give.
    ///
    /// Returns the stage OPEN. It stays open — and this report stays borrowed —
    /// until [`Open::ok`] or [`Open::fail`] closes it, which is what makes a note
    /// written into the middle of a stage a compile error rather than a mangled
    /// line (see the module header).
    pub fn stage(&mut self, which: u32, scope: Scope, name: Arguments<'_>) -> Open<'_, 'a, U> {
        self.last_was_hardware = scope == Scope::HardwareOnly;
        self.scope_code = scope.code();
        // PUBLISHED HERE, so no caller has to remember to. A stage announced to
        // the log but not to `progress` would be invisible to anyone who asks
        // later — which is everyone, once the thing being diagnosed is a world
        // that stopped before its listener arrived.
        crate::progress::begin(which);
        self.ran += 1;
        // ANNOUNCE IT BEFORE ATTEMPTING IT. If this stage hangs, this frame is
        // the last thing a control client hears, and it NAMES what the world was
        // doing — the one diagnosis a stream of completed lines cannot give,
        // because a hung stage never completes its line.
        #[cfg(badge_control)]
        crate::usblog::stage_opened(which, self.scope_code);
        #[cfg(not(badge_control))]
        let _ = which;
        if self.last_was_hardware {
            self.hardware_checks += 1;
        }
        let y = self.y();
        // THE STAGE'S OWN NUMBER, from the `Stage` enum — not a running count.
        //
        // It WAS a count (`self.stage += 1`), and the two disagree the moment a
        // stage does not run. `VERIFY_PAYLOAD` only prints when a payload is
        // corrupt, so on every healthy boot the badge numbered instantiate 6,
        // manifest 7 and execute 8, while the proto, the docs and the runbook
        // all call them 7, 8 and 9.
        //
        // That is two numbering schemes sharing the word "stage" — the exact
        // hazard BRINGUP.md's vocabulary table exists to prevent, reintroduced
        // one layer down. A number that shifts depending on what else happened
        // cannot be quoted, and quoting it ("stage 3 failed") is the whole
        // reason stages are numbered.
        let n = which;
        // `*` marks a check only the board can answer. On the UART it is spelled
        // out, because a log is read later by someone who did not watch the run.
        let mark = if self.last_was_hardware { "*" } else { " " };
        self.draw(y, 0, format_args!("{n}{mark}"), DIM_COLOR);
        self.draw(y, 3, name, NAME_COLOR);
        let _ = write!(self.uart, "{n}. ");
        let _ = self.uart.write_fmt(name);
        if self.last_was_hardware {
            let _ = write!(self.uart, " (hardware-only)");
        }
        let _ = write!(self.uart, " ... ");
        Open { report: self }
    }

    /// The stage worked. `detail` goes to the UART and, if it fits, the screen.
    fn resolve_ok(&mut self, detail: Arguments<'_>) {
        #[cfg(badge_control)]
        crate::usblog::mark(
            dlc_platform_embedded::control::LEVEL_STAGE_OK,
            self.scope_code,
        );
        let y = self.y();
        self.draw(y, RESULT_COL, format_args!("OK"), OK_COLOR);
        // THE DETAIL BELONGS ON THE SCREEN TOO. It went only to the UART, so
        // stage 4 read "payload region  OK" on the badge while the log said
        // "empty" — and the screen narration exists precisely for people without
        // an adapter. Truncated by the line buffer if it does not fit.
        self.draw(y, RESULT_COL + 3, detail, DIM_COLOR);
        let _ = self.uart.write_fmt(detail);
        let _ = writeln!(self.uart, " [OK]");
        if self.last_was_hardware {
            self.hardware_passed += 1;
        }
        self.line += 1;
        self.pause();
    }

    /// The stage failed. **Not necessarily fatal** — the caller decides; some
    /// failures still leave a badge that can report, which is the point of
    /// reporting them rather than halting.
    fn resolve_fail(&mut self, detail: Arguments<'_>) {
        #[cfg(badge_control)]
        crate::usblog::mark(
            dlc_platform_embedded::control::LEVEL_STAGE_FAIL,
            self.scope_code,
        );
        self.failures += 1;
        let y = self.y();
        self.draw(y, RESULT_COL, format_args!("FAIL"), FAIL_COLOR);
        // Same reasoning as resolve_ok: a failure with no reason on screen is
        // the least useful thing this firmware could show.
        self.draw(y + LINE_H, 3, detail, FAIL_COLOR);
        self.line += 1;
        let _ = self.uart.write_fmt(detail);
        let _ = writeln!(self.uart, " [FAIL]");
        self.line += 1;
        self.pause();
    }

    /// Detail that belongs in the log but not on a 40-column screen.
    pub fn note(&mut self, detail: Arguments<'_>) {
        let _ = write!(self.uart, "     ");
        let _ = self.uart.write_fmt(detail);
        let _ = writeln!(self.uart);
    }


    /// A line on the screen with no pass/fail — for a list, like the payloads
    /// found.
    pub fn item(&mut self, detail: Arguments<'_>) {
        let y = self.y();
        self.draw(y, 3, detail, DIM_COLOR);
        let _ = write!(self.uart, "     ");
        let _ = self.uart.write_fmt(detail);
        let _ = writeln!(self.uart);
        self.line += 1;
    }

    /// Lend the screen and the log together, for something that owns the display
    /// for a while — the app menu.
    ///
    /// Both at once rather than two accessors, because the borrow checker is
    /// right: handing them out separately would be two mutable borrows of this
    /// struct, and a caller that wanted to draw AND log would be stuck.
    pub fn with_screen_and_log<R>(
        &mut self,
        f: impl FnOnce(&mut Option<Display>, &mut U) -> R,
    ) -> R {
        let result = f(self.screen, self.uart);
        // Whatever ran owned the whole panel, so the report's line cursor no
        // longer describes what is on screen. Start a fresh page rather than
        // drawing the next stage over a menu.
        self.clear_screen();
        self.line = 1;
        result
    }

    pub fn failed(&self) -> bool {
        self.failures > 0
    }

    /// The verdict, and the last thing drawn as text.
    ///
    /// After this the screen belongs to `show()`, which floods it with the
    /// status colour — so the summary is read, then replaced by the signal that
    /// stays visible across the room.
    pub fn finish(&mut self, status: Status) {
        // PUBLISHED HERE, so no caller has to remember to — the same arrangement
        // that keeps the stage honest. The verdict's other two outlets, a colour
        // and a word, both reach a person; this is the one a client can read.
        crate::progress::verdict(status.code());
        let y = self.y() + LINE_H;
        let color = if self.failures == 0 { OK_COLOR } else { FAIL_COLOR };
        // THE NUMBER WORTH REPORTING is not "all checks passed" — QEMU already
        // said that about most of them. It is how many of the board-only checks
        // passed, because those are the ones nothing else could have answered.
        let (passed, total) = (self.hardware_passed, self.hardware_checks);
        // SAY WHAT THE NUMBER COUNTS, because it does not count what was watched.
        //
        // This read `*5/5` after EIGHT numbered stages had scrolled past, and the
        // first question anyone asks is why those disagree. The answer — that
        // only hardware-only stages are counted, because the rest are already
        // covered by `make qemu` — was true and invisible: the `*` marking those
        // stages appears beside each one, but nobody connects a marker seen
        // eight lines ago to a ratio at the bottom.
        //
        // So both numbers are stated. The stage total is what the reader just
        // watched, and the starred count is the part that carries new
        // information — and neither has to be inferred from the other.
        // Read out before `draw`, which takes `&mut self`.
        let stages = self.ran;
        let stages_ok = self.ran - self.failures;
        self.draw(
            y,
            0,
            format_args!("{}  {stages_ok}/{stages} stages, *{passed}/{total}", status.name()),
            color,
        );
        let _ = writeln!(
            self.uart,
            "verdict: {} — {}/{} stages passed; *{}/{} hardware-only (the rest are QEMU regressions)",
            status.name(),
            self.ran - self.failures,
            self.ran,
            self.hardware_passed,
            self.hardware_checks
        );
        // Long enough to read the summary before the colour takes over — and
        // nothing at all in the default build, where there is no reader.
        if BEAT_MS > 0 {
            cortex_m::asm::delay(self.sys_hz / 1000 * (BEAT_MS * 3));
        }
    }
}

/// A stage that has been ANNOUNCED and not yet resolved.
///
/// Holds the report mutably for exactly as long as the log line is open, so the
/// borrow checker rejects the one call that corrupts the format —
/// `report.note()` between the announcement and its result. There is no runtime
/// cost and no state: the enforcement is entirely the lifetime.
///
/// **Detail that belongs to a stage goes AFTER it**, as a note under a closed
/// line. That is not a workaround for this type; it is the only order that reads
/// correctly, because a stage's result is on the announcement's own line.
#[must_use = "an announced stage must be closed with ok() or fail(), or its line stays open and the next announcement lands inside it"]
pub struct Open<'r, 'a, U: Write> {
    report: &'r mut Report<'a, U>,
}

impl<U: Write> Open<'_, '_, U> {
    /// The stage worked. Closes the line; `detail` goes to the UART and `OK` to
    /// the screen.
    pub fn ok(self, detail: Arguments<'_>) {
        self.report.resolve_ok(detail);
    }

    /// The stage failed. Closes the line. **Not necessarily fatal** — the caller
    /// decides, and some failures still leave a badge that can report.
    pub fn fail(self, detail: Arguments<'_>) {
        self.report.resolve_fail(detail);
    }
}

/// A fixed line buffer, because `format_args!` needs somewhere to land and the
/// heap may not exist yet.
struct TextBuffer {
    bytes: [u8; COLS as usize],
    len: usize,
}

impl TextBuffer {
    fn new() -> Self {
        Self {
            bytes: [0; COLS as usize],
            len: 0,
        }
    }

    fn as_str(&self) -> &str {
        // Only ASCII is ever written here (the font has nothing else), so this
        // cannot split a multi-byte character.
        core::str::from_utf8(&self.bytes[..self.len]).unwrap_or("")
    }
}

impl Write for TextBuffer {
    fn write_str(&mut self, s: &str) -> core::fmt::Result {
        for byte in s.bytes() {
            if self.len == self.bytes.len() {
                // TRUNCATE, never panic. A too-long detail line is a cosmetic
                // problem; a panic during bring-up is a board that stops with no
                // explanation, which is the exact failure this module exists to
                // prevent.
                break;
            }
            // The font covers printable ASCII. Anything else becomes a dot rather
            // than a missing glyph, so a stray byte cannot silently shorten a line.
            self.bytes[self.len] = if (0x20..0x7f).contains(&byte) { byte } else { b'.' };
            self.len += 1;
        }
        Ok(())
    }
}
