package main

// Event bindings, derived from the .proto (host-layer plan Phase 5).
//
// A message that declares `(topic)` IS an event, and this emits the two things
// that stop the topic living in more than one place:
//
//	Go  func (x *StateChangedEvent) Topic() string
//	TS  export const StateChangedTopic = "game.state-changed"
//
// WHY A METHOD RATHER THAN A CONSTANT ON THE GO SIDE. `platform.EmitEvent(msg)`
// has to get the topic from the message itself, and the engine is
// reflection-free for TinyGo — so the message carries it. That also makes
// mismatching a topic and a payload impossible to express: there is no longer a
// call that takes both.
//
// WHAT THIS IS NOT. Unlike `method_id`, a topic is not a dispatch key: nothing
// routes on it and a subscriber matches by string. What makes the schema a
// contract is Decision 34 — once a host RENDERS from a payload, changing the
// message breaks every host drawing it — so the lock below guards the topic
// against silent renames, and `buf breaking` guards the payload as it always
// has.

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"sort"
	"strings"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
)

const topicExt protoreflect.FullName = "devalbo.options.v1.topic"

type event struct {
	message string // Go/TS type name
	topic   string
}

// eventsOf finds every message in a file that declares a topic.
func eventsOf(file *descriptorpb.FileDescriptorProto, resolver *protoregistry.Types) ([]event, error) {
	var out []event
	seen := map[string]string{}

	for _, m := range file.MessageType {
		opts, err := resolveMessageOpts(m.GetOptions(), resolver)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", m.GetName(), err)
		}
		topic, ok := extString(opts, topicExt)
		if !ok || topic == "" {
			continue
		}
		if err := checkTopic(topic); err != nil {
			return nil, fmt.Errorf("%s: topic %w", m.GetName(), err)
		}
		// Two messages on one topic means a subscriber cannot know what it just
		// received — the payload type is decided by the topic or by nothing.
		if prev, dup := seen[topic]; dup {
			return nil, fmt.Errorf("topic %q is declared by both %s and %s — a subscriber could not tell which payload it received", topic, prev, m.GetName())
		}
		seen[topic] = m.GetName()
		out = append(out, event{message: m.GetName(), topic: topic})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].topic < out[j].topic })
	return out, nil
}

// checkTopic rejects topics that cannot be matched or read.
//
// Checked at build time because the failure is otherwise silent: a topic nobody
// can type is a subscription that never fires, which looks exactly like a
// capability that is not wired up.
func checkTopic(topic string) error {
	if strings.TrimSpace(topic) != topic || topic == "" {
		return fmt.Errorf("%q must not be empty or padded with spaces", topic)
	}
	if !strings.Contains(topic, ".") {
		// The convention is `<namespace>.<what-happened>` — `ilc.` for the
		// platform, the app's own name otherwise. A bare word would collide the
		// first time two apps both had "changed".
		return fmt.Errorf("%q needs a namespace, e.g. \"myapp.thing-changed\"", topic)
	}
	for _, r := range topic {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '.', r == '-', r == '_':
		default:
			return fmt.Errorf("%q must be lower-case letters, digits, '.', '-' or '_'", topic)
		}
	}
	return nil
}

func resolveMessageOpts(src *descriptorpb.MessageOptions, resolver *protoregistry.Types) (*descriptorpb.MessageOptions, error) {
	if src == nil {
		return &descriptorpb.MessageOptions{}, nil
	}
	b, err := proto.Marshal(src)
	if err != nil {
		return nil, err
	}
	var out descriptorpb.MessageOptions
	// Custom options arrive as UNKNOWN fields; re-unmarshal with the resolver so
	// they become readable. Same dance as method and field options.
	if err := (proto.UnmarshalOptions{Resolver: resolver}).Unmarshal(b, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// renderEventsGo emits a Topic() method per event message.
func renderEventsGo(file *descriptorpb.FileDescriptorProto, events []event) (string, error) {
	pkg, err := goPackageName(file)
	if err != nil {
		return "", err
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by protoc-gen-dlc-registry. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// source: %s\n//\n", file.GetName())
	fmt.Fprintf(&b, "// Event topics, declared on the messages themselves. A topic written twice is\n")
	fmt.Fprintf(&b, "// a topic that can disagree with itself, which is why nothing hand-writes one.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	for _, e := range events {
		fmt.Fprintf(&b, "// Topic reports where this event is published.\n")
		fmt.Fprintf(&b, "//\n")
		fmt.Fprintf(&b, "// A METHOD, not a constant, so `platform.EmitEvent(msg)` can read it off the\n")
		fmt.Fprintf(&b, "// message without reflection — and so a topic cannot be paired with the wrong\n")
		fmt.Fprintf(&b, "// payload, because there is no call that takes both.\n")
		fmt.Fprintf(&b, "func (*%s) Topic() string { return %q }\n\n", e.message, e.topic)
	}
	return b.String(), nil
}

// renderEventsTS emits a topic constant per event message.
func renderEventsTS(file *descriptorpb.FileDescriptorProto, events []event) (string, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by protoc-gen-dlc-registry. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// source: %s\n//\n", file.GetName())
	fmt.Fprintf(&b, "// Event topics for the web tier — the same strings the engine emits on, from\n")
	fmt.Fprintf(&b, "// the same declaration. Import the constant; never retype the string.\n\n")

	for _, e := range events {
		fmt.Fprintf(&b, "/** Topic for {@link %s}. */\n", e.message)
		fmt.Fprintf(&b, "export const %sTopic = %q;\n", e.message, e.topic)
	}
	return b.String(), nil
}

// checkTopicLock guards event topics the way the id lock guards method ids.
//
// A SIBLING FILE, not the id lock: topics are strings and ids are numbers, and
// one file holding both would need a format that distinguishes them for no gain.
//
// What this protects is narrower than the id lock, and worth stating. A topic is
// not a dispatch key — nothing routes on it. But a subscriber matches by string,
// so renaming one silently stops every subscription firing, and a subscription
// that never fires is indistinguishable from a capability nobody wired up. That
// is the failure this catches. The PAYLOAD's compatibility remains `buf
// breaking`'s job, as it is for every other message.
func checkTopicLock(idLockPath string, current map[string]string) error {
	if idLockPath == "" {
		return nil // no lock configured; topics are unguarded
	}
	path := strings.TrimSuffix(idLockPath, ".lock") + "-topics.lock"

	existing, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		if len(current) == 0 {
			return nil // no events; do not create an empty file
		}
		fmt.Fprintf(os.Stderr, "protoc-gen-dlc-registry: creating topic lock %s\n", path)
		return os.WriteFile(path, []byte(renderTopicLock(current)), 0o644)
	}

	before := parseTopicLock(string(existing))
	var changed, removed []string
	for name, topic := range before {
		now, still := current[name]
		switch {
		case !still:
			removed = append(removed, fmt.Sprintf("%s (was %q)", name, topic))
		case now != topic:
			changed = append(changed, fmt.Sprintf("%s: %q -> %q", name, topic, now))
		}
	}
	sort.Strings(changed)
	sort.Strings(removed)

	if len(changed) > 0 || len(removed) > 0 {
		if os.Getenv("DLC_ID_LOCK_UPDATE") == "" {
			var b strings.Builder
			b.WriteString("event topics changed since " + path + ":\n")
			for _, c := range changed {
				b.WriteString("  " + c + "\n")
			}
			for _, r := range removed {
				b.WriteString("  removed " + r + "\n")
			}
			b.WriteString("\nA renamed topic silently stops every subscriber firing — which looks\n")
			b.WriteString("exactly like a capability nobody wired up. Re-bless deliberately:\n")
			b.WriteString("  DLC_ID_LOCK_UPDATE=1 make gen\n")
			return errors.New(b.String())
		}
	}
	return os.WriteFile(path, []byte(renderTopicLock(current)), 0o644)
}

func renderTopicLock(topics map[string]string) string {
	names := make([]string, 0, len(topics))
	for n := range topics {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# event topic lock — generated by protoc-gen-dlc-registry. COMMIT THIS FILE.\n")
	b.WriteString("# A renamed topic stops every subscriber firing, silently.\n")
	for _, n := range names {
		fmt.Fprintf(&b, "%s %s\n", n, topics[n])
	}
	return b.String()
}

func parseTopicLock(s string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		name, topic, ok := strings.Cut(line, " ")
		if !ok {
			continue
		}
		out[name] = strings.TrimSpace(topic)
	}
	return out
}
