// Code generated by cmd/gen-names from dlc-platform/names/. DO NOT EDIT.
//
// The RULES are here; the REASONS are in names.go, beside the API that uses
// them. Editing this file is a mistake the -check mode will catch.

package platform

// NameComponentMax is the portable profile's longest single component.
const NameComponentMax = 64

// NamePathMax is the portable profile's longest whole path.
const NamePathMax = 255

// ShortStemLength is how many characters a FAT 8.3 short name keeps.
const ShortStemLength = 8

// portableNameChar reports whether a byte may appear in a portable name.
func portableNameChar(c byte) bool {
	return (c >= 'a' && c <= 'z') ||
		(c >= '0' && c <= '9') ||
		c == '-' ||
		c == '_' ||
		c == '.'
}

// shortNameChar maps a byte to what a FAT 8.3 field may hold.
func shortNameChar(c byte) byte {
	if c >= 'a' && c <= 'z' {
		c = c - 'a' + 'A'
	}
	if (c >= 'A' && c <= 'Z') ||
		(c >= '0' && c <= '9') ||
		c == '$' ||
		c == '%' ||
		c == '-' ||
		c == '_' ||
		c == '@' ||
		c == '~' ||
		c == '`' ||
		c == '!' ||
		c == '(' ||
		c == ')' ||
		c == '{' ||
		c == '}' ||
		c == '^' ||
		c == '#' ||
		c == '&' {
		return c
	}
	return '_'
}

// badEdgeFirst reports a byte that may not START a component.
func badEdgeFirst(c byte) bool {
	return c == '.' || c == '-'
}

// badEdgeLast reports a byte that may not END a component.
func badEdgeLast(c byte) bool {
	return c == '.' || c == '-'
}

// reservedDevices are names Windows refuses, with or without an extension.
var reservedDevices = [...]string{
	"con",
	"prn",
	"aux",
	"nul",
	"com1",
	"com2",
	"com3",
	"com4",
	"com5",
	"com6",
	"com7",
	"com8",
	"com9",
	"lpt1",
	"lpt2",
	"lpt3",
	"lpt4",
	"lpt5",
	"lpt6",
	"lpt7",
	"lpt8",
	"lpt9",
}

// profileComponentMax is the per-profile component limit.
func profileComponentMax(p NameProfile) int {
	switch p {
	case "fat":
		return 64
	case "portable":
		return 64
	case "posix":
		return 255
	}
	return 64
}

// profilePathMax is the per-profile path limit.
func profilePathMax(p NameProfile) int {
	switch p {
	case "fat":
		return 255
	case "portable":
		return 255
	case "posix":
		return 4096
	}
	return 255
}

// knownWorlds is the registry, minus the two non-worlds.
var knownWorlds = [...]World{
	"native",
	"browser",
	"badge-normal",
	"badge-minimal",
}

// worldNameProfile maps a world onto its rule set. Both non-worlds and
// anything unrecognised FAIL CLOSED onto the strictest profile.
func worldNameProfile(w World) NameProfile {
	switch w {
	case "native":
		return "portable"
	case "browser":
		return "portable"
	case "badge-normal":
		return "fat"
	case "badge-minimal":
		return "fat"
	}
	return ProfilePortable
}
