// Code generated by cmd/gen-protocol from dlc-platform/protocol/FRAMING.json. DO NOT EDIT.

package platform

// FrameMagic marks the start of a frame in a stream that is mostly log text.
var FrameMagic = []byte("DLCC")

const (
	// A client asking a world something.
	FrameKindRequest = 1
	// A world's answer, correlated by request_id.
	FrameKindResponse = 2
	// A LogLine, pushed to a subscriber.
	FrameKindLog = 3
	// A periodic WorldState, so silence means something.
	FrameKindHeartbeat = 4
)

// FNV-1a, little-endian on the wire. Never zero — see the JSON.
const (
	ChecksumOffsetBasis uint32 = 0x811C9DC5
	ChecksumPrime       uint32 = 0x01000193
)

const (
	// The largest payload a frame may carry. Bounded so a corrupt length cannot
	// make a world allocate against a number it read off a wire.
	MaxPayload = 8192

	// The largest app request a world accepts for pass-through. Bigger than any
	// widget can collect — a person types one field — and smaller than a frame,
	// because this bounds what is COPIED into a fixed slot while it waits.
	MaxRequest = 256

	// Room for the fields AROUND a payload: a verb, a correlation id, their
	// tags. Named rather than folded into the sums so it is obvious what the
	// spare bytes are for.
	EnvelopeSlack = 32

	// The longest line the log will frame. Bounded by the panel and the report format.
	MaxLogLine = 96

	// How many framed notices a world keeps for a client that has not read them.
	// About four screens of bring-up; beyond that the oldest go and the count of
	// what went is reported rather than quietly dropped.
	NoticeSlots = 40

	// The longest sentence a stack-built refusal may carry. Everything needing
	// more than this needs a heap and can wait for one.
	MaxRefusalText = 64

	// Everything a frame costs beyond its payload.
	//
	// magic_bytes + kind_bytes + length_bytes + checksum_bytes
	FrameOverhead = 11

	// What a world holds while reassembling an inbound frame. A frame larger
	// than this can never complete, so a world REFUSES one that says it is —
	// rather than sliding bytes forever while the sender waits.
	//
	// frame_overhead + max_request + envelope_slack
	Inbound = 299

	// One framed LogLine, and the slot that holds it.
	//
	// frame_overhead + max_log_line + envelope_slack
	NoticeFrame = 139

	// A ControlResponse carrying one sentence and a correlation id.
	//
	// max_refusal_text + envelope_slack
	RefusalBody = 96

	// The same, framed — the answer a world can give before it has a heap.
	//
	// frame_overhead + refusal_body
	RefusalFrame = 107
)
