// gen-names emits the name-rule tables into Go and Rust from one specification.
//
// WHY. Apps are Go, the badge host is Rust, and no library spans them — so the
// rules were written twice and `VECTORS.tsv` existed to DETECT the drift. This
// removes the drift instead: both implementations are generated from
// `dlc-platform/names/RULES.json` and `WORLDS.tsv`, so they cannot disagree about
// a character class, a limit, or a reserved name.
//
// The vectors are still worth having, and they now check something different:
// that the generated code means what the rules INTENDED. Codegen makes the two
// implementations identical; it cannot make them correct.
//
// WHAT IS NOT GENERATED: the prose, the API, and the set-level logic. Every rule
// has a reason, and the reasons live beside the API in the hand-written files. A
// generator that emitted explanations too would flatten the part that makes the
// profile learnable — so this emits tables and predicates, nothing else.
//
//	go run ./cmd/gen-names            # write the generated files
//	go run ./cmd/gen-names -check     # fail if they are stale (CI)
package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type limits struct {
	Component int `json:"component"`
	Path      int `json:"path"`
}

type charClass struct {
	Ranges      [][]string `json:"ranges"`
	Extra       string     `json:"extra"`
	Replacement string     `json:"replacement"`
	StemLength  int        `json:"stem_length"`
}

type badEdge struct {
	First string `json:"first"`
	Last  string `json:"last"`
}

type rules struct {
	Limits          map[string]limits `json:"limits"`
	PortableChars   charClass         `json:"portable_chars"`
	ShortNameChars  charClass         `json:"short_name_chars"`
	BadEdge         badEdge           `json:"bad_edge"`
	ReservedDevices []string          `json:"reserved_devices"`
}

// world is one row of WORLDS.tsv.
type world struct {
	ID      string
	Profile string
	// Notes is the registry's third column — carried so the generated proto can
	// say what a world IS, rather than listing six bare identifiers.
	Notes string
}

const banner = "Code generated by cmd/gen-names from dlc-platform/names/. DO NOT EDIT."

func main() {
	check := flag.Bool("check", false, "fail if the generated files are stale")
	flag.Parse()

	root := findRoot()
	spec := loadRules(filepath.Join(root, "dlc-platform/names/RULES.json"))
	worlds := loadWorlds(filepath.Join(root, "dlc-platform/names/WORLDS.tsv"))

	outputs := map[string][]byte{
		filepath.Join(root, "dlc-platform/names_gen.go"):              renderGo(spec, worlds),
		filepath.Join(root, "dlc-platform/embedded/src/names_gen.rs"): renderRust(spec, worlds),
		// THE PROTO ENUM IS GENERATED TOO, from the same rows.
		//
		// It was hand-written beside this file and drifted the first time anyone
		// used it: adding the Badger needed an edit HERE, an edit in the .proto,
		// and an edit in the test that checks they agree — three places to add
		// one world, which is how the enum came to have no name for `browser` in
		// its first draft.
		filepath.Join(root, "dlc-platform/proto/devalbo/ilc/v1/world_name.proto"): renderProto(worlds),
	}

	stale := []string{}
	for path, want := range outputs {
		got, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(got, want) {
			stale = append(stale, path)
			if !*check {
				if err := os.WriteFile(path, want, 0o644); err != nil {
					fatal("writing %s: %v", path, err)
				}
				fmt.Printf("  wrote %s\n", mustRel(root, path))
			}
		}
	}

	if *check {
		// THE GUARD THAT MAKES CODEGEN WORTH ANYTHING. Without it, someone edits a
		// generated file by hand, the two implementations diverge again, and the
		// single source has quietly become a third copy.
		if len(stale) > 0 {
			sort.Strings(stale)
			for _, path := range stale {
				fmt.Fprintf(os.Stderr, "  x stale: %s\n", mustRel(root, path))
			}
			fatal("generated files are out of date — run `make gen-names`")
		}
		fmt.Println("  generated name rules are up to date")
		return
	}
	if len(stale) == 0 {
		fmt.Println("  generated name rules already up to date")
	}
}

// ---------------------------------------------------------------------------
// Go
// ---------------------------------------------------------------------------

func renderGo(spec rules, worlds []world) []byte {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("// %s", banner)
	p("//")
	p("// The RULES are here; the REASONS are in names.go, beside the API that uses")
	p("// them. Editing this file is a mistake the -check mode will catch.")
	p("")
	p("package platform")
	p("")

	portable := spec.Limits["portable"]
	p("// NameComponentMax is the portable profile's longest single component.")
	p("const NameComponentMax = %d", portable.Component)
	p("")
	p("// NamePathMax is the portable profile's longest whole path.")
	p("const NamePathMax = %d", portable.Path)
	p("")
	p("// ShortStemLength is how many characters a FAT 8.3 short name keeps.")
	p("const ShortStemLength = %d", spec.ShortNameChars.StemLength)
	p("")

	p("// portableNameChar reports whether a byte may appear in a portable name.")
	p("func portableNameChar(c byte) bool {")
	p("\treturn %s", goCharExpr(spec.PortableChars))
	p("}")
	p("")

	p("// shortNameChar maps a byte to what a FAT 8.3 field may hold.")
	p("func shortNameChar(c byte) byte {")
	p("\tif c >= 'a' && c <= 'z' {")
	p("\t\tc = c - 'a' + 'A'")
	p("\t}")
	p("\tif %s {", goCharExpr(spec.ShortNameChars))
	p("\t\treturn c")
	p("\t}")
	p("\treturn %s", quoteByteGo(spec.ShortNameChars.Replacement))
	p("}")
	p("")

	p("// badEdgeFirst reports a byte that may not START a component.")
	p("func badEdgeFirst(c byte) bool {")
	p("\treturn %s", goByteSet("c", spec.BadEdge.First))
	p("}")
	p("")
	p("// badEdgeLast reports a byte that may not END a component.")
	p("func badEdgeLast(c byte) bool {")
	p("\treturn %s", goByteSet("c", spec.BadEdge.Last))
	p("}")
	p("")

	p("// reservedDevices are names Windows refuses, with or without an extension.")
	p("var reservedDevices = [...]string{")
	for _, device := range spec.ReservedDevices {
		p("\t%q,", device)
	}
	p("}")
	p("")

	p("// profileComponentMax is the per-profile component limit.")
	p("func profileComponentMax(p NameProfile) int {")
	p("\tswitch p {")
	for _, name := range sortedKeys(spec.Limits) {
		p("\tcase %q:", name)
		p("\t\treturn %d", spec.Limits[name].Component)
	}
	p("\t}")
	p("\treturn %d", portable.Component)
	p("}")
	p("")

	p("// profilePathMax is the per-profile path limit.")
	p("func profilePathMax(p NameProfile) int {")
	p("\tswitch p {")
	for _, name := range sortedKeys(spec.Limits) {
		p("\tcase %q:", name)
		p("\t\treturn %d", spec.Limits[name].Path)
	}
	p("\t}")
	p("\treturn %d", portable.Path)
	p("}")
	p("")

	p("// knownWorlds is the registry, minus the two non-worlds.")
	p("var knownWorlds = [...]World{")
	for _, w := range worlds {
		p("\t%q,", w.ID)
	}
	p("}")
	p("")

	p("// worldNameProfile maps a world onto its rule set. Both non-worlds and")
	p("// anything unrecognised FAIL CLOSED onto the strictest profile.")
	p("func worldNameProfile(w World) NameProfile {")
	p("\tswitch w {")
	for _, w := range worlds {
		p("\tcase %q:", w.ID)
		p("\t\treturn %q", w.Profile)
	}
	p("\t}")
	p("\treturn ProfilePortable")
	p("}")

	return []byte(b.String())
}

func goCharExpr(class charClass) string {
	parts := []string{}
	for _, r := range class.Ranges {
		parts = append(parts, fmt.Sprintf("(c >= %s && c <= %s)", quoteByteGo(r[0]), quoteByteGo(r[1])))
	}
	for _, c := range []byte(class.Extra) {
		parts = append(parts, fmt.Sprintf("c == %s", quoteByteGo(string(c))))
	}
	return strings.Join(parts, " ||\n\t\t")
}

func goByteSet(v, set string) string {
	parts := []string{}
	for _, c := range []byte(set) {
		parts = append(parts, fmt.Sprintf("%s == %s", v, quoteByteGo(string(c))))
	}
	return strings.Join(parts, " || ")
}

func quoteByteGo(s string) string {
	if s == "'" {
		return `'\''`
	}
	if s == `\` {
		return `'\\'`
	}
	return "'" + s + "'"
}

// ---------------------------------------------------------------------------
// Rust
// ---------------------------------------------------------------------------

// renderProto emits the WorldName enum from the registry.
//
// The proto spelling of a world id is the id in SCREAMING_SNAKE with the enum's
// prefix: `badge-normal` becomes `WORLD_NAME_BADGE_NORMAL`. `undefined` is the
// zero value and is spelled `UNSPECIFIED` there, because proto's linter requires
// that and the registry was written with the other word — the same fact, two
// vocabularies, reconciled here rather than in anybody's head.
func renderProto(worlds []world) []byte {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("// %s", banner)
	p("")
	p("syntax = \"proto3\";")
	p("")
	p("package devalbo.ilc.v1;")
	p("")
	p("option go_package = \"github.com/devalbo/devalbo-ilc/dlc-platform/gen/go/devalbo/ilc/v1;ilcv1\";")
	p("")
	p("// Which host slot an app is running in.")
	p("//")
	p("// GENERATED FROM dlc-platform/names/WORLDS.tsv, which is the registry Go and")
	p("// Rust are also generated from. A world added there appears here, in the")
	p("// same commit, without anybody remembering to.")
	p("//")
	p("// `WorldName` rather than `World`, because a `WorldManifest` describes a")
	p("// world and an enum called `World` inside it reads as though it IS one. The")
	p("// values are literally names: this file is a table of them.")
	p("enum WorldName {")
	// THE TWO NON-WORLDS FIRST, and they are different in a way that matters.
	// The registry documents both at length; they are not rows in `worlds`
	// because they are the absence of one.
	p("  // Nobody declared one. The DEFAULT and the common case: an app that runs")
	p("  // everywhere has no reason to name a world.")
	p("  //")
	p("  // Spelled UNSPECIFIED here and `undefined` in the registry, because")
	p("  // proto's linter requires the former. Same fact, two words.")
	p("  WORLD_NAME_UNSPECIFIED = 0;")
	p("  // Declared, and this build does not recognise it. Distinct from")
	p("  // UNSPECIFIED: something was said and could not be understood, which the")
	p("  // badge's payload region makes routine — payloads outlive the firmware.")
	p("  WORLD_NAME_UNKNOWN = 1;")
	for i, w := range worlds {
		name := strings.ToUpper(strings.ReplaceAll(w.ID, "-", "_"))
		if w.Notes != "" {
			p("  // %s", w.Notes)
		}
		p("  WORLD_NAME_%s = %d;", name, i+2)
	}
	p("}")
	return []byte(b.String())
}

func renderRust(spec rules, worlds []world) []byte {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("// %s", banner)
	p("//")
	p("// The RULES are here; the REASONS are in names.rs, beside the API that uses")
	p("// them. Editing this file is a mistake the -check mode will catch.")
	p("")
	p("#![allow(dead_code)]")
	p("")

	portable := spec.Limits["portable"]
	p("/// The portable profile's longest single component.")
	p("pub const COMPONENT_MAX: usize = %d;", portable.Component)
	p("")
	p("/// The portable profile's longest whole path.")
	p("pub const PATH_MAX: usize = %d;", portable.Path)
	p("")
	p("/// How many characters a FAT 8.3 short name keeps.")
	p("pub const SHORT_STEM_LEN: usize = %d;", spec.ShortNameChars.StemLength)
	p("")

	p("/// Whether a byte may appear in a portable name.")
	p("pub const fn portable_name_char(c: u8) -> bool {")
	p("    matches!(c, %s)", rustPattern(spec.PortableChars))
	p("}")
	p("")

	p("/// Map a byte to what a FAT 8.3 field may hold.")
	p("pub const fn short_name_char(c: u8) -> u8 {")
	p("    let c = c.to_ascii_uppercase();")
	p("    if matches!(c, %s) {", rustPattern(spec.ShortNameChars))
	p("        c")
	p("    } else {")
	p("        %s", quoteByteRust(spec.ShortNameChars.Replacement))
	p("    }")
	p("}")
	p("")

	p("/// A byte that may not START a component.")
	p("pub const fn bad_edge_first(c: u8) -> bool {")
	p("    matches!(c, %s)", rustByteSet(spec.BadEdge.First))
	p("}")
	p("")
	p("/// A byte that may not END a component.")
	p("pub const fn bad_edge_last(c: u8) -> bool {")
	p("    matches!(c, %s)", rustByteSet(spec.BadEdge.Last))
	p("}")
	p("")

	p("/// Names Windows refuses, with or without an extension.")
	p("pub const RESERVED_DEVICES: [&str; %d] = [", len(spec.ReservedDevices))
	for _, device := range spec.ReservedDevices {
		p("    %q,", device)
	}
	p("];")
	p("")

	p("/// Per-profile component limit.")
	p("pub const fn profile_component_max(profile: &str) -> usize {")
	for _, name := range sortedKeys(spec.Limits) {
		p("    if str_eq(profile, %q) {", name)
		p("        return %d;", spec.Limits[name].Component)
		p("    }")
	}
	p("    COMPONENT_MAX")
	p("}")
	p("")

	p("/// Per-profile path limit.")
	p("pub const fn profile_path_max(profile: &str) -> usize {")
	for _, name := range sortedKeys(spec.Limits) {
		p("    if str_eq(profile, %q) {", name)
		p("        return %d;", spec.Limits[name].Path)
		p("    }")
	}
	p("    PATH_MAX")
	p("}")
	p("")

	// THE WIRE NUMBERS TOO, matching world_name.proto exactly.
	//
	// The badge hand-declared these beside its other proto constants, which made
	// the registry's numbering something a person had to copy correctly — and the
	// numbering is not arbitrary: it is this file's row order plus the two
	// non-worlds. Emitting both from the same loop is what makes them agree.
	p("/// `WorldName` in world_name.proto. Generated from the same rows, so the")
	p("/// badge cannot report a number the schema does not name.")
	p("pub const WORLD_NAME_UNSPECIFIED: u32 = 0;")
	p("pub const WORLD_NAME_UNKNOWN: u32 = 1;")
	for i, w := range worlds {
		p("pub const WORLD_NAME_%s: u32 = %d;", strings.ToUpper(strings.ReplaceAll(w.ID, "-", "_")), i+2)
	}
	p("")

	p("/// The registry, minus the two non-worlds.")
	p("pub const KNOWN_WORLDS: [&str; %d] = [", len(worlds))
	for _, w := range worlds {
		p("    %q,", w.ID)
	}
	p("];")
	p("")

	p("/// A world's rule set. Both non-worlds and anything unrecognised FAIL CLOSED")
	p("/// onto the strictest profile.")
	p("pub const fn world_name_profile(world: &str) -> &'static str {")
	for _, w := range worlds {
		p("    if str_eq(world, %q) {", w.ID)
		p("        return %q;", w.Profile)
		p("    }")
	}
	p("    \"portable\"")
	p("}")
	p("")

	p("/// `str` comparison usable in a `const fn`, which `==` is not.")
	p("const fn str_eq(a: &str, b: &str) -> bool {")
	p("    let (a, b) = (a.as_bytes(), b.as_bytes());")
	p("    if a.len() != b.len() {")
	p("        return false;")
	p("    }")
	p("    let mut i = 0;")
	p("    while i < a.len() {")
	p("        if a[i] != b[i] {")
	p("            return false;")
	p("        }")
	p("        i += 1;")
	p("    }")
	p("    true")
	p("}")

	return []byte(b.String())
}

func rustPattern(class charClass) string {
	parts := []string{}
	for _, r := range class.Ranges {
		parts = append(parts, fmt.Sprintf("%s..=%s", quoteByteRust(r[0]), quoteByteRust(r[1])))
	}
	for _, c := range []byte(class.Extra) {
		parts = append(parts, quoteByteRust(string(c)))
	}
	return strings.Join(parts, " | ")
}

func rustByteSet(set string) string {
	parts := []string{}
	for _, c := range []byte(set) {
		parts = append(parts, quoteByteRust(string(c)))
	}
	return strings.Join(parts, " | ")
}

func quoteByteRust(s string) string {
	switch s {
	case "'":
		return `b'\''`
	case `\`:
		return `b'\\'`
	}
	return "b'" + s + "'"
}

// ---------------------------------------------------------------------------

func loadRules(path string) rules {
	raw, err := os.ReadFile(path)
	if err != nil {
		fatal("reading %s: %v", path, err)
	}
	var spec rules
	if err := json.Unmarshal(raw, &spec); err != nil {
		fatal("parsing %s: %v", path, err)
	}
	if len(spec.ReservedDevices) == 0 || spec.ShortNameChars.StemLength == 0 {
		fatal("%s is missing required fields", path)
	}
	return spec
}

// loadWorlds reads WORLDS.tsv, skipping the two NON-worlds: `undefined` and
// `unknown` are not registry entries, they are what a lookup RETURNS, and
// emitting them as known worlds would make `IsRealWorld` true for both.
func loadWorlds(path string) []world {
	file, err := os.Open(path)
	if err != nil {
		fatal("reading %s: %v", path, err)
	}
	defer file.Close()

	out := []world{}
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") || !strings.Contains(line, "\t") {
			continue
		}
		id, rest, _ := strings.Cut(line, "\t")
		profile, notes, _ := strings.Cut(rest, "\t")
		if id == "undefined" || id == "unknown" {
			continue
		}
		out = append(out, world{
			ID:      id,
			Profile: strings.TrimSpace(profile),
			Notes:   strings.TrimSpace(notes),
		})
	}
	if err := scanner.Err(); err != nil {
		fatal("scanning %s: %v", path, err)
	}
	if len(out) == 0 {
		fatal("%s named no worlds", path)
	}
	return out
}

func findRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		fatal("%v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "dlc-platform/names/RULES.json")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fatal("could not find the repo root (no dlc-platform/names/RULES.json above %s)", dir)
		}
		dir = parent
	}
}

func mustRel(root, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return rel
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

// sortedKeys keeps generated output DETERMINISTIC. Go map iteration is
// randomised, so without this the generator would emit a different byte sequence
// each run and `-check` would fail at random — which reads as "someone edited a
// generated file" and is the worst possible false alarm for this tool.
func sortedKeys(m map[string]limits) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
