package main

import (
	"fmt"
	"go/format"
	"strings"

	"google.golang.org/protobuf/types/descriptorpb"
)

// renderEnumsRust emits every enum value in a file as a plain constant.
//
// # Why constants and not a Rust enum
//
// The badge hand-decodes protobuf: it reads a varint off a wire and compares it.
// A Rust enum would need a fallible conversion at every boundary and would make
// an unrecognised value — which a payload built against a newer schema WILL send
// — into an error rather than a number to skip. Constants match how the wire
// actually works.
func renderEnumsRust(file *descriptorpb.FileDescriptorProto) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by protoc-gen-dlc-registry from %s. DO NOT EDIT.\n", file.GetName())
	b.WriteString("//\n// Every enum value in the file, as constants a `no_std` decoder can compare\n// against. Hand-copying these is what put DISPLAY=2 and UART=3 into a badge\n// that then reported the wrong outlet for a day.\n//\n// NO INNER ATTRIBUTES: this is `include!`d into a module, where `#![...]` is a\n// syntax error. A generated file has to be valid in the place it is used, not\n// only on its own.\n\n")
	for _, e := range file.EnumType {
		if len(e.Value) == 0 {
			continue
		}
		fmt.Fprintf(&b, "// %s\n", e.GetName())
		for _, v := range e.Value {
			fmt.Fprintf(&b, "pub const %s: u32 = %d;\n", v.GetName(), v.GetNumber())
		}
		b.WriteString("\n")
	}
	return b.String()
}

// renderEnumsTS emits the same for the web tier's hand-written encoders.
func renderEnumsTS(file *descriptorpb.FileDescriptorProto) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by protoc-gen-dlc-registry from %s. DO NOT EDIT.\n", file.GetName())
	b.WriteString("//\n// For the hand-written encoders in web/, which cannot import the generated\n// message types without pulling a decoder into a worker that only needs\n// numbers.\n\n")
	for _, e := range file.EnumType {
		if len(e.Value) == 0 {
			continue
		}
		fmt.Fprintf(&b, "// %s\n", e.GetName())
		for _, v := range e.Value {
			fmt.Fprintf(&b, "export const %s = %d;\n", v.GetName(), v.GetNumber())
		}
		b.WriteString("\n")
	}
	return b.String()
}

// screamingSnake turns `WorldState` into `WORLD_STATE`.
func screamingSnake(name string) string {
	var b strings.Builder
	for i, r := range name {
		if r >= 'A' && r <= 'Z' && i > 0 {
			b.WriteByte('_')
		}
		if r >= 'a' && r <= 'z' {
			r = r - 'a' + 'A'
		}
		b.WriteRune(r)
	}
	return b.String()
}

// eachMessage walks a file's messages, including nested ones.
func eachMessage(prefix string, msgs []*descriptorpb.DescriptorProto, f func(name string, m *descriptorpb.DescriptorProto)) {
	for _, m := range msgs {
		name := m.GetName()
		if prefix != "" {
			name = prefix + "_" + name
		}
		f(name, m)
		eachMessage(name, m.NestedType, f)
	}
}

// renderFieldsRust emits every message's FIELD NUMBERS as constants.
//
// # Why this exists, and why it is not the same problem as the enums above
//
// The badge hand-encodes and hand-decodes protobuf — it has no allocator for
// most of its bring-up and no room for a reflection-based codec — so its writers
// name field numbers directly:
//
//	put_varint_field(&mut out, 17, self.phase)
//
// That `17` is the wire identity of `WorldState.phase`, transcribed from the
// .proto by hand. The enum work above removed transcribed VALUES; this removes
// transcribed IDENTITIES, and the failure mode is worse. A wrong enum value
// mislabels one field; a wrong field number puts the bytes somewhere else
// entirely, so a reader either skips them as unknown or — if the number happens
// to belong to another field of compatible wire type — decodes them as something
// they are not, silently.
//
// Renumbering a field is already a breaking change. The point is that it should
// break the BUILD rather than the badge.
func renderFieldsRust(file *descriptorpb.FileDescriptorProto) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by protoc-gen-dlc-registry from %s. DO NOT EDIT.\n", file.GetName())
	b.WriteString("//\n// Field NUMBERS, for the hand-written encoders that cannot use a generated\n// message type. See `renderFieldsRust` for why a transcribed field number is\n// worse than a transcribed enum value.\n//\n// NO INNER ATTRIBUTES: this is `include!`d into a module.\n\n")
	eachMessage("", file.MessageType, func(name string, m *descriptorpb.DescriptorProto) {
		if len(m.Field) == 0 {
			return
		}
		fmt.Fprintf(&b, "// %s\n", name)
		for _, f := range m.Field {
			fmt.Fprintf(&b, "pub const F_%s_%s: u32 = %d;\n",
				screamingSnake(name), strings.ToUpper(f.GetName()), f.GetNumber())
		}
		b.WriteString("\n")
	})
	return b.String()
}

// renderFieldsTS emits the same for the web tier's hand-written encoders.
func renderFieldsTS(file *descriptorpb.FileDescriptorProto) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by protoc-gen-dlc-registry from %s. DO NOT EDIT.\n", file.GetName())
	b.WriteString("//\n// Field numbers, for the hand-written encoders in web/.\n\n")
	eachMessage("", file.MessageType, func(name string, m *descriptorpb.DescriptorProto) {
		if len(m.Field) == 0 {
			return
		}
		fmt.Fprintf(&b, "// %s\n", name)
		for _, f := range m.Field {
			fmt.Fprintf(&b, "export const F_%s_%s = %d;\n",
				screamingSnake(name), strings.ToUpper(f.GetName()), f.GetNumber())
		}
		b.WriteString("\n")
	})
	return b.String()
}

// renderFieldsGo emits field numbers for Go's hand-written decoders.
//
// # Why Go needs these at all
//
// It should not have to: a descriptor carries field numbers, and asking is
// always right. But this project generates Go with `protoc-gen-go-lite`, which
// omits reflection — that is the point of it, since the badge's own tooling and
// the wasm tiers cannot afford a reflection-based codec. So `ProtoReflect()`
// does not exist, and a hand-decoder in badgectl has the same problem the badge
// has: a literal it transcribed from the .proto.
func renderFieldsGo(file *descriptorpb.FileDescriptorProto, pkg string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by protoc-gen-dlc-registry from %s. DO NOT EDIT.\n\n", file.GetName())
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("// Field numbers, for hand-written decoders. `protoc-gen-go-lite` omits\n// reflection, so a descriptor cannot be asked at runtime.\n\n")
	b.WriteString("const (\n")
	eachMessage("", file.MessageType, func(name string, m *descriptorpb.DescriptorProto) {
		if len(m.Field) == 0 {
			return
		}
		fmt.Fprintf(&b, "\t// %s\n", name)
		for _, f := range m.Field {
			fmt.Fprintf(&b, "\tF_%s_%s = %d\n",
				screamingSnake(name), strings.ToUpper(f.GetName()), f.GetNumber())
		}
		b.WriteString("\n")
	})
	b.WriteString(")\n")
	// THROUGH gofmt, because a generator that emits unformatted Go produces a
	// file that fails the formatting check the moment it is written — a
	// generator whose output nobody can commit. `gen-protocol` learned this
	// first; the lesson did not travel to this file until CI said so.
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		// The unformatted text is still valid Go and still better than nothing;
		// the formatting check will name the file.
		return b.String()
	}
	return string(out)
}
