package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/types/descriptorpb"
)

// renderEnumsRust emits every enum value in a file as a plain constant.
//
// # Why constants and not a Rust enum
//
// The badge hand-decodes protobuf: it reads a varint off a wire and compares it.
// A Rust enum would need a fallible conversion at every boundary and would make
// an unrecognised value — which a payload built against a newer schema WILL send
// — into an error rather than a number to skip. Constants match how the wire
// actually works.
func renderEnumsRust(file *descriptorpb.FileDescriptorProto) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by protoc-gen-dlc-registry from %s. DO NOT EDIT.\n", file.GetName())
	b.WriteString("//\n// Every enum value in the file, as constants a `no_std` decoder can compare\n// against. Hand-copying these is what put DISPLAY=2 and UART=3 into a badge\n// that then reported the wrong outlet for a day.\n//\n// NO INNER ATTRIBUTES: this is `include!`d into a module, where `#![...]` is a\n// syntax error. A generated file has to be valid in the place it is used, not\n// only on its own.\n\n")
	for _, e := range file.EnumType {
		if len(e.Value) == 0 {
			continue
		}
		fmt.Fprintf(&b, "// %s\n", e.GetName())
		for _, v := range e.Value {
			fmt.Fprintf(&b, "pub const %s: u32 = %d;\n", v.GetName(), v.GetNumber())
		}
		b.WriteString("\n")
	}
	return b.String()
}

// renderEnumsTS emits the same for the web tier's hand-written encoders.
func renderEnumsTS(file *descriptorpb.FileDescriptorProto) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by protoc-gen-dlc-registry from %s. DO NOT EDIT.\n", file.GetName())
	b.WriteString("//\n// For the hand-written encoders in web/, which cannot import the generated\n// message types without pulling a decoder into a worker that only needs\n// numbers.\n\n")
	for _, e := range file.EnumType {
		if len(e.Value) == 0 {
			continue
		}
		fmt.Fprintf(&b, "// %s\n", e.GetName())
		for _, v := range e.Value {
			fmt.Fprintf(&b, "export const %s = %d;\n", v.GetName(), v.GetNumber())
		}
		b.WriteString("\n")
	}
	return b.String()
}
