#!/usr/bin/env bash
#
# ci.sh — the ONE entry point for continuous integration, whoever is running it.
#
#   ./scripts/ci.sh fast     structure + unit + fmt/vet          (~1 min, no wasm)
#   ./scripts/ci.sh full     fast + engine boundary + web tier + badge firmware
#   ./scripts/ci.sh all      full + the B1 de-risking spikes     (slow; nightly)
#
# THREE SLICES OF `full`, for a provider that can run jobs in parallel. Together
# they cover exactly what `full` covers, and each is a WHOLE toolchain rather than
# an arbitrary cut:
#
#   ./scripts/ci.sh native    fast + the engine boundary (Go, TinyGo; no browser)
#   ./scripts/ci.sh web       the browser tier (npm, Chromium)
#   ./scripts/ci.sh embedded  bare metal + the Rust runtime + badge firmware
#
# WHY SLICES AND NOT PARALLEL STEPS INSIDE ONE RUN. The working tree is shared
# mutable state on purpose: `verify-parity-selftest.sh` injects `engine/zz_*.go`
# to prove the parity check can fail, `gen/` is regenerated by several steps,
# `build/` is one directory, and `dlc` is one binary at the root. Two suites in one
# checkout clobber each other. Separate jobs get separate checkouts, so the hazard
# does not exist rather than being managed.
#
# **A slice is not faster, it is EARLIER.** Splitting cannot reduce total work and
# each job pays its own cold toolchain, so the win is wall-clock feedback, and it
# is worth less than warming the caches: B2 measured 410s cold and 89s warm in
# consecutive runs of the same checks. Cache first, split second.
#
# DELIBERATELY PROVIDER-AGNOSTIC. Nothing here — and nothing in the suites it
# calls — knows about GitHub, GitLab, Jenkins, or anything else. No provider env
# vars, no per-provider caching hooks, no annotations. A CI config is a thin
# adapter that installs devbox and runs one of the lines above; switching
# providers means rewriting that adapter, not the tests.
#
# The corollary that matters more: **CI runs exactly what you run locally.**
# `./scripts/ci.sh full` on your laptop is the same command, in the same
# toolchain, producing the same result — so "passes locally, fails in CI" is a
# devbox problem, not a mystery.
#
# Toolchain: provisioned by devbox. If you are already inside `devbox shell`
# this runs commands directly; otherwise it wraps each one in `devbox run`.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 2

TIER="${1:-full}"
if [ -t 1 ]; then G=$'\033[32m'; R=$'\033[31m'; B=$'\033[1m'; Z=$'\033[0m'; else G=''; R=''; B=''; Z=''; fi

# Inside devbox already? Then don't re-enter it for every step (slow, and it
# resets the working directory).
if command -v tinygo >/dev/null 2>&1 && command -v buf >/dev/null 2>&1; then
	run() { "$@"; }
else
	if ! command -v devbox >/dev/null 2>&1; then
		echo "ci: devbox not found — install it (https://www.jetify.com/docs/devbox/installing-devbox)" >&2
		echo "ci: or run inside a shell that already provides go, tinygo, buf, node" >&2
		exit 2
	fi
	run() { devbox run -- "$@"; }
fi

# Environment sanity: a leftover parity-drift probe is `//go:build tinygo` and
# empties the template FS, so native stays green while every wasm build ships
# nothing. Cheap to check, confusing to debug.
if ls engine/zz_*.go >/dev/null 2>&1; then
	printf "${R}✗ stray engine/zz_*.go — a self-test died and left it; wasm builds will embed no templates${Z}\n"
	ls engine/zz_*.go
	exit 2
fi

failed=()
# WHERE THE TIME GOES, because until this existed nobody knew. Two `full` runs
# differing only in which build artifacts were present took 336s and 728s, which
# is a wider spread than most individual steps — so "what should we parallelise"
# had no answer that was not a guess. Printed as a sorted summary at the end, next
# to the verdict, because that is the part anyone actually reads.
timings=()
LOGS="$(mktemp -d)"
trap 'rm -rf "$LOGS"' EXIT

# Each step streams as it runs AND is captured, so a failure can be re-printed at
# the very end. On a CI page the interesting output is thousands of lines up,
# which is how a B2 failure went unexamined while a B3 failure got all the
# attention — the summary is the only part anyone reads.
step() { # <label> <command...>
	local label="$1"; shift
	local log="$LOGS/$(printf '%s' "$label" | tr -c 'a-zA-Z0-9' '_')"
	local started=$SECONDS
	printf "\n${B}▶ %s${Z}\n" "$label"
	if "$@" 2>&1 | tee "$log"; then
		printf "${G}✓ %s${Z} (%ss)\n" "$label" "$((SECONDS - started))"
	else
		printf "${R}✗ %s${Z} (%ss)\n" "$label" "$((SECONDS - started))"
		failed+=("$label")
	fi
	timings+=("$((SECONDS - started)) $label")
}

# Anything interactive must refuse to be interactive here. `dlc new` prompts for
# tiers at a terminal, and a suite run from a developer's shell HAS a terminal —
# so a script that forgot `--tiers` blocked the whole run on a prompt instead of
# failing. Setting CI makes that a named error. Playwright reads it too, and
# stops reusing a stray dev server.
export CI=1

# ---- fast: no wasm toolchain, no browser --------------------------------
group_fast() {
step "repo structure (B0)"      run make test-b0
step "shell lint" ./scripts/lint-scripts.sh
step "formatting"               run ./scripts/check-fmt.sh
# gen/ is gitignored — a fresh clone (CI) has no bindings until we produce them.
# B3/B2's wasm targets call `make gen` themselves; vet + unit tests do not, so
# without this step a clean tree fails with "no matching versions for …/gen/go/…".
step "codegen"                  run make gen
# THE FRAMING IS GENERATED TOO, into three languages from one spec. Checked
# beside `gen` because a stale constant here is the same class of failure as a
# stale binding: two implementations that agree in review and not on the wire.
step "framing constants"        run make verify-protocol
step "vet"                      run go vet ./engine/... ./cmd/... ./hosts/...
# hosts/ is in scope as well as engine/: it vets here but did not TEST here, so
# hosts/native/manifest_test.go — the dlc.toml slot gate — would have passed CI
# by never running. Vet and test should cover the same tree.
#
# ...AND THEN IT HAPPENED AGAIN, to cmd/. The line above vetted `./cmd/...` while
# this one did not test it, so cmd/gen-names' tests — the guard that stops the
# generated Go and Rust name rules drifting apart — would have passed CI by never
# running. The rule is not "remember hosts/"; it is that these two lists must be
# THE SAME LIST, and they are now.
step "unit tests"               run go test ./engine/... ./cmd/... ./hosts/...
# dlc-platform is a SEPARATE MODULE (§16.4), so `./...` from the repo root does
# not reach it — and it had therefore never run its own tests in CI at all, while
# holding dispatch, path containment, BFT, and the environment manifest. Found
# while adding the index: six existing test files, none of them executed here.
# `go test -C` is what crosses a module boundary without a subshell cd.
step "platform unit tests"      run go test -C dlc-platform ./...
# WINDOWS, checked from here rather than assumed. A cross-build catches the whole
# class this project is exposed to — a unix-only import, a build tag that has no
# Windows counterpart — for the price of a compile, on every push, with no
# Windows runner involved. It does NOT check runtime behaviour: path separators,
# case-insensitive filenames and reserved device names only show up when the code
# runs, which is the `windows` job in .github/workflows/ci.yml.
step "windows cross-build"      run env GOOS=windows GOARCH=amd64 go build -C dlc-platform ./...
step "windows cross-build (dlc)" run env GOOS=windows GOARCH=amd64 go build ./engine/... ./hosts/native/...
}

# ---- the engine boundary: unit + parity + the scaffold ------------------
# B2 covers unit + native↔wasm parity + the parity self-test + the scaffold
# actually building and running. **It is 70% of a `full` run** — 410s of 583s
# measured, and `make test-b2` now prints which of its checks that is.
group_boundary() {
step "engine boundary (B2)"  run make test-b2
}

# ---- the browser tier ---------------------------------------------------
group_web() {
step "web tier (B3)"         run make test-b3
}

# ---- Rust: the no_std runtime, and the firmware that consumes it --------
group_embedded() {
	# BARE METAL, checked by LINKING rather than by reasoning about build tags.
	# The capability seam selects a file by constraint, and a wrong constraint is
	# invisible to vet, to every unit test, and to both wasm builds — it surfaces
	# only as a linker error, and only for a target nothing else here builds.
	# `//go:build tinygo` did exactly this: TinyGo compiles for boards too, so the
	# wasip2 half was selected for a chip with no host to import from. Falsified
	# in place before being trusted — restore the old tag and this step goes red.
	# In `full` rather than `fast` because it needs the TinyGo toolchain.
	step "bare-metal link (rp2350)" run ./scripts/check-baremetal.sh
	# THE SAME CLASS, one language over — and NEITHER profile was covered before
	# this. `dlc-platform-embedded` builds two ways, and the parity runner is a
	# separate crate that depends on neither, so a `use std::` in a portable
	# module or a break in `host.rs` would pass everything here and surface only
	# when somebody cross-compiled for a board. Falsified before being trusted:
	# adding a `std::` to command.rs turns both no_std targets red.
	# Two no_std targets because D8's "one Rust family for badge and ESP" is
	# otherwise a hope rather than a check. The firmware crates that CONSUME the
	# library are slower, and are built at the end of this tier.
	step "embedded runtime builds" run ./scripts/check-embedded.sh
	# ON EVERY PUSH as of 2026-08-15, moved out of `all`. It was nightly for its
	# cost — a fresh wasmtime build per target — which meant a firmware break was
	# found by a cron job the next morning rather than by the push that caused it,
	# and the lib builds above cannot see one: an API change keeps a library green
	# and breaks its callers, which is exactly how `PulleyWidth` went missing.
	# ONE artifact, TWO consumers. Both the QEMU harness and the badge firmware
	# read build/hello.pulley32.cwasm — the harness through its build.rs — so this
	# single AOT run feeds both, and neither can run bytes the other did not.
	# Nothing produced it here while this tier was nightly-only, which is why the
	# harness failed to compile the day it moved into `full`.
	step "badge payload artifact" run make badge-cwasm
	# REQUIRE_BADGE_PAYLOAD, because two of the five badge modes need a real
	# .cwasm and were SKIPPED-IF-ABSENT — which, with a path that pointed outside
	# the repo, meant skipped always, on every machine and every nightly, with the
	# step still green. The artifact is built above; demanding it here is what
	# makes that a red step instead of a line of output nobody reads.
	step "embedded firmware builds" run env REQUIRE_BADGE_PAYLOAD=1 ./scripts/check-embedded.sh --firmware
}

# ---- all: the de-risking spikes -----------------------------------------
group_slow() {
	# Slow (several TinyGo builds + a headless browser) and rarely broken by
	# day-to-day work, so this belongs on a schedule rather than every push —
	# which is also what DEVALBO-DLC-TEST-STEPS.md recommends.
	step "de-risking spikes (B1)" run make test-b1
	# Resolves a FRESH devbox environment for a scaffolded project (its @latest
	# packages are unlocked), so it needs the network and costs minutes. It also
	# fails for a reason nothing else can see: a tool the template forgets to
	# declare, which this repo's own shell has been quietly supplying.
	#
	# `run` gives it OUR toolchain to build dlc with; the scrub-and-re-enter for
	# the SCAFFOLD's devbox.json happens inside the script, after that.
	step "scaffold's own environment" run ./scripts/verify-scaffold-env.sh
	# Also network-bound, and for a related reason: every other check passes
	# --platform-path, which resolves the platform from this tree and never asks
	# a remote anything. This is the only check that consults the pinned ref, so
	# it is the only one that notices a bumped constant with no pushed tag.
	step "the pinned platform ref resolves" run ./scripts/verify-platform-ref.sh
}

# ---- what each tier is, in one place ------------------------------------
# `native | web | embedded` together cover exactly `full`, so a provider running
# them as three jobs loses no coverage — assert that by reading this table, which
# is the only place tiers are composed.
#
# THE ONE ORDERING DEPENDENCY: `badge-cwasm` AOT-compiles hello's component, which
# the web tier happens to build. `full` therefore runs the embedded group after
# the web group and gets it for free, while the `embedded` slice — which runs no
# browser — names it as a step of its own.
case "$TIER" in
fast) group_fast ;;
native) group_fast; group_boundary ;;
web) group_web ;;
embedded)
	step "hello component (for the badge payload)" run make hello-component
	group_embedded
	;;
full) group_fast; group_boundary; group_web; group_embedded ;;
all) group_fast; group_boundary; group_web; group_embedded; group_slow ;;
*)
	echo "ci: unknown tier '$TIER' — expected fast | full | all | native | web | embedded" >&2
	exit 2
	;;
esac

echo
echo "-------------------------------------------------"
printf "%s total, slowest steps:\n" "${SECONDS}s"
printf '%s\n' "${timings[@]}" | sort -rn | head -6 |
	while read -r took rest; do printf "  %5ss  %s\n" "$took" "$rest"; done
echo "-------------------------------------------------"
if [ ${#failed[@]} -eq 0 ]; then
	printf "${G}✓ ci (%s) green${Z}\n" "$TIER"
	exit 0
fi
printf "${R}✗ ci (%s): %d step(s) failed${Z}\n" "$TIER" "${#failed[@]}"
for f in "${failed[@]}"; do echo "    - $f"; done

# Re-print the tail of every failed step, so the summary at the bottom of the log
# contains the actual errors rather than pointing at them.
for f in "${failed[@]}"; do
	log="$LOGS/$(printf '%s' "$f" | tr -c 'a-zA-Z0-9' '_')"
	printf "\n${R}--- last 40 lines of: %s ---${Z}\n" "$f"
	tail -40 "$log" 2>/dev/null || echo "(no output captured)"
done
exit 1
