// gen-protocol turns dlc-platform/protocol/FRAMING.json into the framing
// constants for every language that speaks the control channel.
//
// # Why this exists
//
// The framing had two hand-written implementations — Rust on the badge, Go in
// badgectl — and agreed only because one person wrote both. WebSerial makes
// three and badge-to-badge makes four, at which point "they agree" is a claim
// nobody can check.
//
// This is the same shape as cmd/gen-names, and for the same reason: generating
// two implementations removes the drift, where writing both and testing them
// only DETECTS it.
//
// # Derived sizes
//
// The spec states relationships (`inbound = frame_overhead + max_request +
// envelope_slack`) and this evaluates them. A literal cannot be checked against
// the thing it was chosen for — which is how a 512-byte reply buffer met a
// 600-byte answer, sent the first 512 bytes, and left a client waiting forever
// for a completion that could not come.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type spec struct {
	Magic    string         `json:"magic"`
	Header   map[string]int `json:"header"`
	Kinds    []named        `json:"kinds"`
	Checksum checksum       `json:"checksum"`
	Limits   []limit        `json:"limits"`
	Derived  []derived      `json:"derived"`
}

type named struct {
	Name  string `json:"name"`
	Value int    `json:"value"`
	Doc   string `json:"doc"`
}

type checksum struct {
	Algorithm   string `json:"algorithm"`
	OffsetBasis uint32 `json:"offset_basis"`
	Prime       uint32 `json:"prime"`
	NeverZero   bool   `json:"never_zero"`
}

type limit struct {
	Name  string `json:"name"`
	Value int    `json:"value"`
	Doc   any    `json:"doc"`
}

type derived struct {
	Name string `json:"name"`
	Expr string `json:"expr"`
	Doc  any    `json:"doc"`
}

const banner = "Code generated by cmd/gen-protocol from dlc-platform/protocol/FRAMING.json. DO NOT EDIT."

func main() {
	check := flag.Bool("check", false, "fail if the generated files are stale")
	flag.Parse()

	root := findRoot()
	s := load(filepath.Join(root, "dlc-platform/protocol/FRAMING.json"))
	values := evaluate(s)

	outputs := map[string][]byte{
		filepath.Join(root, "dlc-platform/embedded/src/limits_gen.rs"): renderRust(s, values),
		filepath.Join(root, "dlc-platform/protocol_gen.go"):            renderGo(s, values),
		filepath.Join(root, "dlc-platform/web/protocol-gen.ts"):        renderTS(s, values),
	}

	stale := []string{}
	for path, want := range outputs {
		got, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(got, want) {
			stale = append(stale, path)
			if !*check {
				if err := os.WriteFile(path, want, 0o644); err != nil {
					fatal("writing %s: %v", path, err)
				}
				fmt.Printf("  wrote %s\n", mustRel(root, path))
			}
		}
	}

	if *check && len(stale) > 0 {
		// THE GUARD THAT MAKES CODEGEN WORTH ANYTHING. Without it somebody edits a
		// generated file by hand, the implementations diverge again, and the
		// single source has quietly become a fourth copy.
		sort.Strings(stale)
		for _, path := range stale {
			fmt.Fprintf(os.Stderr, "  stale: %s\n", mustRel(root, path))
		}
		fatal("run `make gen-protocol` and commit the result")
	}
}

// evaluate resolves the derived sizes, so a relationship is stated once here and
// nowhere in three languages.
func evaluate(s spec) map[string]int {
	out := map[string]int{}
	for k, v := range s.Header {
		out[k] = v
	}
	for _, l := range s.Limits {
		out[l.Name] = l.Value
	}
	for _, d := range s.Derived {
		total := 0
		for _, term := range strings.Split(d.Expr, "+") {
			term = strings.TrimSpace(term)
			v, ok := out[term]
			if !ok {
				fatal("%s: unknown term %q", d.Name, term)
			}
			total += v
		}
		out[d.Name] = total
	}
	return out
}

func docLines(doc any) []string {
	switch v := doc.(type) {
	case string:
		if v == "" {
			return nil
		}
		return []string{v}
	case []any:
		out := []string{}
		for _, line := range v {
			out = append(out, fmt.Sprint(line))
		}
		return out
	}
	return nil
}

func comment(prefix string, lines []string) string {
	var b strings.Builder
	for _, l := range lines {
		if l == "" {
			b.WriteString(strings.TrimRight(prefix, " ") + "\n")
			continue
		}
		b.WriteString(prefix + l + "\n")
	}
	return b.String()
}

func renderRust(s spec, v map[string]int) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "//! %s\n//!\n//! Every size the control channel commits to. See the JSON for why each is\n//! what it is; the relationships are evaluated there and land here as numbers.\n\n", banner)
	fmt.Fprintf(&b, "/// Marks the start of a frame in a stream that is mostly log text.\npub const MAGIC: [u8; %d] = *b\"%s\";\n\n", len(s.Magic), s.Magic)
	for _, k := range s.Kinds {
		if k.Doc != "" {
			fmt.Fprintf(&b, "/// %s\n", k.Doc)
		}
		fmt.Fprintf(&b, "pub const KIND_%s: u8 = %d;\n", strings.ToUpper(k.Name), k.Value)
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "/// FNV-1a, little-endian on the wire. Never zero — see the JSON.\npub const CHECKSUM_OFFSET_BASIS: u32 = 0x%08X;\npub const CHECKSUM_PRIME: u32 = 0x%08X;\n\n", s.Checksum.OffsetBasis, s.Checksum.Prime)
	for _, l := range s.Limits {
		b.WriteString(comment("/// ", docLines(l.Doc)))
		fmt.Fprintf(&b, "pub const %s: usize = %d;\n\n", strings.ToUpper(l.Name), v[l.Name])
	}
	for _, d := range s.Derived {
		b.WriteString(comment("/// ", docLines(d.Doc)))
		fmt.Fprintf(&b, "///\n/// `%s`\npub const %s: usize = %d;\n\n", d.Expr, strings.ToUpper(d.Name), v[d.Name])
	}
	return []byte(b.String())
}

func renderGo(s spec, v map[string]int) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s\n\npackage platform\n\n", banner)
	fmt.Fprintf(&b, "// FrameMagic marks the start of a frame in a stream that is mostly log text.\nvar FrameMagic = []byte(%q)\n\n", s.Magic)
	b.WriteString("const (\n")
	for _, k := range s.Kinds {
		if k.Doc != "" {
			fmt.Fprintf(&b, "\t// %s\n", k.Doc)
		}
		fmt.Fprintf(&b, "\tFrameKind%s = %d\n", title(k.Name), k.Value)
	}
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "// FNV-1a, little-endian on the wire. Never zero — see the JSON.\nconst (\n\tChecksumOffsetBasis uint32 = 0x%08X\n\tChecksumPrime       uint32 = 0x%08X\n)\n\n", s.Checksum.OffsetBasis, s.Checksum.Prime)
	b.WriteString("const (\n")
	for _, l := range s.Limits {
		b.WriteString(comment("\t// ", docLines(l.Doc)))
		fmt.Fprintf(&b, "\t%s = %d\n\n", title(l.Name), v[l.Name])
	}
	for _, d := range s.Derived {
		b.WriteString(comment("\t// ", docLines(d.Doc)))
		fmt.Fprintf(&b, "\t//\n\t// %s\n\t%s = %d\n\n", d.Expr, title(d.Name), v[d.Name])
	}
	b.WriteString(")\n")
	// THROUGH gofmt, because a generator that emits unformatted Go produces a
	// file that fails the formatting check the moment it is written — which is a
	// generator whose output nobody can commit.
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		fatal("formatting the generated Go: %v", err)
	}
	return out
}

func renderTS(s spec, v map[string]int) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s\n//\n// The web tier's half of the framing: WebSerial speaks this, and so will\n// anything else in a browser that talks to a device.\n\n", banner)
	fmt.Fprintf(&b, "export const FRAME_MAGIC = new Uint8Array([%s]);\n\n", byteList(s.Magic))
	for _, k := range s.Kinds {
		if k.Doc != "" {
			fmt.Fprintf(&b, "/** %s */\n", k.Doc)
		}
		fmt.Fprintf(&b, "export const KIND_%s = %d;\n", strings.ToUpper(k.Name), k.Value)
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "/** FNV-1a, little-endian on the wire. Never zero — see the JSON. */\nexport const CHECKSUM_OFFSET_BASIS = 0x%08X;\nexport const CHECKSUM_PRIME = 0x%08X;\n\n", s.Checksum.OffsetBasis, s.Checksum.Prime)
	for _, l := range s.Limits {
		b.WriteString(comment("// ", docLines(l.Doc)))
		fmt.Fprintf(&b, "export const %s = %d;\n\n", strings.ToUpper(l.Name), v[l.Name])
	}
	for _, d := range s.Derived {
		b.WriteString(comment("// ", docLines(d.Doc)))
		fmt.Fprintf(&b, "//\n// %s\nexport const %s = %d;\n\n", d.Expr, strings.ToUpper(d.Name), v[d.Name])
	}
	return []byte(b.String())
}

func byteList(s string) string {
	parts := make([]string, 0, len(s))
	for _, c := range []byte(s) {
		parts = append(parts, fmt.Sprintf("0x%02X", c))
	}
	return strings.Join(parts, ", ")
}

func title(name string) string {
	out := ""
	for _, part := range strings.Split(name, "_") {
		if part == "" {
			continue
		}
		out += strings.ToUpper(part[:1]) + part[1:]
	}
	return out
}

func load(path string) spec {
	raw, err := os.ReadFile(path)
	if err != nil {
		fatal("reading %s: %v", path, err)
	}
	var s spec
	if err := json.Unmarshal(raw, &s); err != nil {
		fatal("parsing %s: %v", path, err)
	}
	return s
}

func findRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		fatal("cwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fatal("no go.mod above the working directory")
		}
		dir = parent
	}
}

func mustRel(root, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return rel
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-protocol: "+format+"\n", args...)
	os.Exit(1)
}
