// Code generated by cmd/gen-protocol from dlc-platform/protocol/FRAMING.json. DO NOT EDIT.
//
// The web tier's half of the framing: WebSerial speaks this, and so will
// anything else in a browser that talks to a device.

export const FRAME_MAGIC = new Uint8Array([0x44, 0x4C, 0x43, 0x43]);

/** A client asking a world something. */
export const KIND_REQUEST = 1;
/** A world's answer, correlated by request_id. */
export const KIND_RESPONSE = 2;
/** A LogLine, pushed to a subscriber. */
export const KIND_LOG = 3;
/** A periodic WorldState, so silence means something. */
export const KIND_HEARTBEAT = 4;

/** FNV-1a, little-endian on the wire. Never zero — see the JSON. */
export const CHECKSUM_OFFSET_BASIS = 0x811C9DC5;
export const CHECKSUM_PRIME = 0x01000193;

// The largest payload a frame may carry. Bounded so a corrupt length cannot
// make a world allocate against a number it read off a wire.
export const MAX_PAYLOAD = 8192;

// The largest app request a world accepts for pass-through. Bigger than any
// widget can collect — a person types one field — and smaller than a frame,
// because this bounds what is COPIED into a fixed slot while it waits.
export const MAX_REQUEST = 256;

// Room for the fields AROUND a payload: a verb, a correlation id, their
// tags. Named rather than folded into the sums so it is obvious what the
// spare bytes are for.
export const ENVELOPE_SLACK = 32;

// The longest line the log will frame. Bounded by the panel and the report format.
export const MAX_LOG_LINE = 96;

// How many framed notices a world keeps for a client that has not read them.
// About four screens of bring-up; beyond that the oldest go and the count of
// what went is reported rather than quietly dropped.
export const NOTICE_SLOTS = 40;

// The longest sentence a stack-built refusal may carry. Everything needing
// more than this needs a heap and can wait for one.
export const MAX_REFUSAL_TEXT = 64;

// Everything a frame costs beyond its payload.
//
// magic_bytes + kind_bytes + length_bytes + checksum_bytes
export const FRAME_OVERHEAD = 11;

// What a world holds while reassembling an inbound frame. A frame larger
// than this can never complete, so a world REFUSES one that says it is —
// rather than sliding bytes forever while the sender waits.
//
// frame_overhead + max_request + envelope_slack
export const INBOUND = 299;

// One framed LogLine, and the slot that holds it.
//
// frame_overhead + max_log_line + envelope_slack
export const NOTICE_FRAME = 139;

// A ControlResponse carrying one sentence and a correlation id.
//
// max_refusal_text + envelope_slack
export const REFUSAL_BODY = 96;

// The same, framed — the answer a world can give before it has a heap.
//
// frame_overhead + refusal_body
export const REFUSAL_FRAME = 107;

