package main

// `dlc gen` — a TOOLCHAIN verb (Decision 30): it runs buf and writes generated
// code, so it lives host-side and never enters the engine.
//
// Its one job beyond wrapping buf is turning `dlc.toml` into Go the engine can
// import. That is how the manifest reaches the engine WITHOUT the engine ever
// reading a config file: the values are resolved at build time, exactly as
// method ids are. The engine keeps no parser, no file dependency, and no way to
// disagree with the manifest.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

func runGen(args []string) error {
	if len(args) > 0 {
		return fmt.Errorf("gen: unexpected argument %q", args[0])
	}
	m, err := loadManifest()
	if err != nil {
		return err
	}

	// buf first: the config package is small, but a failed codegen should not
	// leave a half-updated tree behind it.
	if _, err := exec.LookPath("buf"); err != nil {
		return fmt.Errorf("gen: buf not found on PATH — run inside `devbox shell`")
	}
	cmd := exec.Command("buf", "generate")
	cmd.Dir = "proto"
	cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("gen: buf generate: %w", err)
	}

	return writeConfigPackage(m)
}

// writeConfigPackage emits gen/go/dlcconfig from the manifest.
func writeConfigPackage(m *Manifest) error {
	dir := filepath.Join("gen", "go", "dlcconfig")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by `dlc gen` from dlc.toml. DO NOT EDIT.\n//\n")
	b.WriteString("// The engine imports this instead of reading dlc.toml, because it also runs\n")
	b.WriteString("// in a browser tab and on devices where that file does not exist. Editing\n")
	b.WriteString("// these values means editing dlc.toml and re-running `dlc gen`.\n")
	b.WriteString("package dlcconfig\n\n")
	b.WriteString("const (\n")
	fmt.Fprintf(&b, "\t// Name is the project name from [project].\n\tName = %s\n", strconv.Quote(m.Name))
	fmt.Fprintf(&b, "\t// Version is the project version from [project].\n\tVersion = %s\n", strconv.Quote(m.Version))
	b.WriteString(")\n\n")
	b.WriteString("// Version string apps hand to platform.SetVersion.\n")
	b.WriteString("func Display() string { return Name + \" \" + Version }\n")

	out := filepath.Join(dir, "config.go")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Fprintln(os.Stderr, "gen: wrote "+out)
	return nil
}
